/**
 * DTCG token resolver (theme × mode) for the TypeScript tools — the part of tools/tokens.py the parser needs:
 * theme ids, the resolved light/dark tree of a theme, public and CSS token names.
 *
 * Runs under Node's type stripping: annotations only.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { REPO_ROOT } from './root.ts';

export const THEMES_DIR: string = join(REPO_ROOT, 'tokens', 'themes');
export const MODES: readonly string[] = ['light', 'dark'];
const REF = /^\{([a-zA-Z0-9.\-]+)\}$/;
const RESERVED = new Set(['$type', '$description', '$value', '$extensions', '$deprecated']);

export type TokenEntry = { $value: unknown; $type: string | null; raw?: unknown };
type Tree = Record<string, unknown>;

function deepMerge(a: Tree, b: Tree): Tree {
  for (const [k, v] of Object.entries(b)) {
    const existing = a[k];
    if (isTree(v) && isTree(existing)) deepMerge(existing, v);
    else a[k] = v;
  }
  return a;
}

function isTree(v: unknown): v is Tree {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/** Theme ids, generated by tools/theme.py into tokens/themes/<id>/. */
export function themes(): string[] {
  return readdirSync(THEMES_DIR)
    .filter((name) => existsSync(join(THEMES_DIR, name, 'base.json')))
    .sort();
}

export function modes(theme: string): string[] {
  return MODES.filter((m) => existsSync(join(THEMES_DIR, theme, `${m}.json`)));
}

/** Throws an ENOENT error (Python's FileNotFoundError) when the theme has not been derived. */
export function loadTree(theme: string, mode: string): Tree {
  const tree: Tree = {};
  for (const f of [join(THEMES_DIR, theme, 'base.json'), join(THEMES_DIR, theme, `${mode}.json`)]) {
    deepMerge(tree, JSON.parse(readFileSync(f, 'utf8')) as Tree);
  }
  return tree;
}

/** `{ 'color.foreground.default': {$value, $type}, … }` with inherited $type. */
export function flatten(tree: Tree): Record<string, TokenEntry> {
  const out: Record<string, TokenEntry> = {};
  const walk = (node: Tree, path: string[], inherited: string | null): void => {
    const t = (Object.hasOwn(node, '$type') ? node.$type : inherited) as string | null;
    if (Object.hasOwn(node, '$value')) {
      out[path.join('.')] = { $value: node.$value, $type: t };
      return;
    }
    for (const [k, v] of Object.entries(node)) {
      if (RESERVED.has(k) || !isTree(v)) continue;
      walk(v, [...path, k], t);
    }
  };
  walk(tree, [], null);
  return out;
}

export function resolve(flat: Record<string, TokenEntry>): Record<string, TokenEntry> {
  const get = (path: string, seen: string[]): unknown => {
    if (seen.includes(path)) throw new Error(`Circular token reference: ${[...seen, path].join(' -> ')}`);
    if (!Object.hasOwn(flat, path)) throw new Error(`Unknown token reference {${path}} (referenced from ${seen.length ? seen[seen.length - 1] : '?'})`);
    const v = (flat[path] as TokenEntry).$value;
    const m = typeof v === 'string' ? REF.exec(v) : null;
    return m ? get(m[1] as string, [...seen, path]) : v;
  };
  const out: Record<string, TokenEntry> = {};
  for (const [p, t] of Object.entries(flat)) out[p] = { $value: get(p, []), $type: t.$type, raw: t.$value };
  return out;
}

export function loadTheme(theme: string, mode: string): Record<string, TokenEntry> {
  return resolve(flatten(loadTree(theme, mode)));
}

/** color.foreground.default → color.foreground (the name components use). */
export function publicName(path: string): string {
  const parts = path.split('.');
  return (parts[parts.length - 1] === 'default' ? parts.slice(0, -1) : parts).join('.');
}

export function cssName(path: string): string {
  const kebab = publicName(path).replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `--${kebab}`;
}
