/**
 * DTCG token resolver (theme × mode) for the tools: theme ids, the resolved light/dark tree of a theme,
 * and the public, CSS and camelCase names of a token path. The port of tools/tokens.py, which step 6 of
 * process/typescript-and-currency.md deleted with mcp/server.py, its last reader.
 *
 * Runs under Node's type stripping: annotations only.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { pyStr } from './py.ts';
import { REPO_ROOT } from './root.ts';

export const THEMES_DIR: string = join(REPO_ROOT, 'tokens', 'themes');
export const MODES: readonly string[] = ['light', 'dark'];
const REF = /^\{([a-zA-Z0-9.\-]+)\}$/;
const RESERVED = new Set(['$type', '$description', '$value', '$extensions', '$deprecated']);

export type TokenEntry = { $value: unknown; $type: string | null; raw?: unknown };
export type Tree = Record<string, unknown>;

/** `tokens._deep_merge`: `b` over `a` in place, recursing into branches both sides hold as trees. */
export function deepMerge(a: Tree, b: Tree): Tree {
  for (const [k, v] of Object.entries(b)) {
    const existing = a[k];
    if (isTree(v) && isTree(existing)) deepMerge(existing, v);
    else a[k] = v;
  }
  return a;
}

function isTree(v: unknown): v is Tree {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/** Theme ids, generated by tools/theme.ts into tokens/themes/<id>/. */
export function themes(): string[] {
  return readdirSync(THEMES_DIR)
    .filter((name) => existsSync(join(THEMES_DIR, name, 'base.json')))
    .sort();
}

export function modes(theme: string): string[] {
  return MODES.filter((m) => existsSync(join(THEMES_DIR, theme, `${m}.json`)));
}

/** Throws an ENOENT error (Python's FileNotFoundError) when the theme has not been derived. */
export function loadTree(theme: string, mode: string): Tree {
  const tree: Tree = {};
  for (const f of [join(THEMES_DIR, theme, 'base.json'), join(THEMES_DIR, theme, `${mode}.json`)]) {
    deepMerge(tree, JSON.parse(readFileSync(f, 'utf8')) as Tree);
  }
  return tree;
}

/** `{ 'color.foreground.default': {$value, $type}, … }` with inherited $type. */
export function flatten(tree: Tree): Record<string, TokenEntry> {
  const out: Record<string, TokenEntry> = {};
  const walk = (node: Tree, path: string[], inherited: string | null): void => {
    const t = (Object.hasOwn(node, '$type') ? node.$type : inherited) as string | null;
    if (Object.hasOwn(node, '$value')) {
      out[path.join('.')] = { $value: node.$value, $type: t };
      return;
    }
    for (const [k, v] of Object.entries(node)) {
      if (RESERVED.has(k) || !isTree(v)) continue;
      walk(v, [...path, k], t);
    }
  };
  walk(tree, [], null);
  return out;
}

export function resolve(flat: Record<string, TokenEntry>): Record<string, TokenEntry> {
  const get = (path: string, seen: string[]): unknown => {
    if (seen.includes(path)) throw new Error(`Circular token reference: ${[...seen, path].join(' -> ')}`);
    if (!Object.hasOwn(flat, path)) throw new Error(`Unknown token reference {${path}} (referenced from ${seen.length ? seen[seen.length - 1] : '?'})`);
    const v = (flat[path] as TokenEntry).$value;
    const m = typeof v === 'string' ? REF.exec(v) : null;
    return m ? get(m[1] as string, [...seen, path]) : v;
  };
  const out: Record<string, TokenEntry> = {};
  for (const [p, t] of Object.entries(flat)) out[p] = { $value: get(p, []), $type: t.$type, raw: t.$value };
  return out;
}

export function loadTheme(theme: string, mode: string): Record<string, TokenEntry> {
  return resolve(flatten(loadTree(theme, mode)));
}

/** color.foreground.default → color.foreground (the name components use). */
export function publicName(path: string): string {
  const parts = path.split('.');
  return (parts[parts.length - 1] === 'default' ? parts.slice(0, -1) : parts).join('.');
}

/** One DTCG shadow as the CSS `box-shadow` value (`tokens.shadow_css`); `spread` defaults to `0px`. */
export function shadowCss(v: Record<string, unknown>): string {
  const spread = Object.hasOwn(v, 'spread') ? v.spread : '0px';
  return `${pyStr(v.offsetX)} ${pyStr(v.offsetY)} ${pyStr(v.blur)} ${pyStr(spread)} ${pyStr(v.color)}`;
}

export function cssName(path: string): string {
  const kebab = publicName(path).replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `--${kebab}`;
}

/** color.action.primary.background → colorActionPrimaryBackground (the name React Native uses). */
export function camelName(path: string): string {
  const [first, ...rest] = publicName(path).replace(/-/g, '.').split('.') as [string, ...string[]];
  return first + rest.map((s) => s.slice(0, 1).toUpperCase() + s.slice(1)).join('');
}

/** A naming doc's `tokens` block, as the emitted-name helpers read it (schema/naming.ts, job 628). */
export type TokensNaming = { readonly cssPrefix?: string | undefined; readonly rename?: Readonly<Record<string, string>> | undefined };

/** The dotted path a token is emitted under: the brand path `rename` gives its public name, or the public name itself. */
export function emittedPath(path: string, naming: TokensNaming = {}): string {
  const name = publicName(path);
  return naming.rename !== undefined && Object.hasOwn(naming.rename, name) ? (naming.rename[name] as string) : name;
}

/** The custom property a token is emitted as: `--<cssPrefix>-<kebab of the brand path>`, or `cssName` when the doc
 *  neither renames the token nor sets a prefix. */
export function emittedCssName(path: string, naming: TokensNaming = {}): string {
  const name = cssName(emittedPath(path, naming));
  return naming.cssPrefix === undefined ? name : `--${naming.cssPrefix}-${name.slice(2)}`;
}

/** The JS/RN object key and Swift name a token is emitted as. `cssPrefix` never reaches it: a JS key lives on an
 *  object, so it has no global namespace to protect. */
export function emittedCamelName(path: string, naming: TokensNaming = {}): string {
  return camelName(emittedPath(path, naming));
}

/** tokens/build.mjs's `THEME_MEMBERS`: the `Theme` members a token accessor in TokenRef.swift would shadow. Copied so a
 *  naming doc is refused before a build runs; tools/__tests__/naming_tokens.test.ts keeps the two sets equal. */
export const THEME_MEMBERS: ReadonlySet<string> = new Set([
  'definition', 'colorScheme', 'id', 'title', 'color', 'dimension', 'duration', 'animation',
  'fontWeight', 'fontFamily', 'number', 'shadow',
]);
