import { view } from './storybook.requires';
import './theme-addon';

// storybook.requires.ts is (re)generated by `sb-rn-get-stories` (also on `expo start` via withStorybook)
// from main.ts; it registers the stories under packages/rn/src and the on-device addons.
const StorybookUIRoot = view.getStorybookUI({
  enableWebsockets: false,
});

export default StorybookUIRoot;
