// Generated by tools/behavior_tests.ts from the `behavior` block of the Callout doc. Do not edit.
import { describe, expect, test, vi } from 'vitest';
import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Callout } from '../src/Callout';
import type { CalloutProps } from '../src/Callout';
import meta from '../src/Callout.stories';

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const INTERACTIVE = "button, a[href], input:not([type=\"hidden\"]), select, textarea, [role=\"button\"], [role=\"checkbox\"], [role=\"switch\"], [role=\"radio\"], [role=\"textbox\"], [role=\"searchbox\"], [role=\"spinbutton\"], [role=\"combobox\"], [role=\"slider\"], [role=\"link\"], [role=\"tab\"], [role=\"menuitem\"], [role=\"menuitemcheckbox\"], [role=\"menuitemradio\"], [role=\"option\"], [role=\"treeitem\"], [role=\"scrollbar\"]";
const OWN_ROLE = "dialog, [role=\"dialog\"], [role=\"alertdialog\"], [role=\"combobox\"], [role=\"grid\"], [role=\"listbox\"], [role=\"menu\"], [role=\"menubar\"], [role=\"radiogroup\"], [role=\"tablist\"], [role=\"tree\"], [role=\"treegrid\"]";
function activatable(el: Element | null, root: Element | null): HTMLElement {
  if (el === null || el === root || el.matches(INTERACTIVE) || el.matches(OWN_ROLE)) return el as HTMLElement;
  return (el.querySelector(INTERACTIVE) ?? el) as HTMLElement;
}
function focusedPart(el: Element | null, root: Element | null): Element | null {
  return el === null || document.activeElement === el ? el : activatable(el, root);
}

function setup(given: Partial<CalloutProps> = {}) {
  const events = {
    onDismiss: vi.fn(),
  };
  const props = { ...meta.args, ...given, onDismiss: events.onDismiss };
  const utils = render(<Callout {...props} />);
  const user = userEvent.setup();
  const s = {
    ...utils,
    user,
    events,
    props,
    root: () => (document.querySelector('[data-ds="Alert"]') ?? screen.queryByRole('status') ?? utils.container.firstElementChild) as HTMLElement,
    container: () => (screen.queryByRole('status') ?? s.root()) as HTMLElement,
    dismissButton: () => (document.querySelector('[data-part="dismissButton"]') ?? s.root()),
    rerender: (next: Partial<CalloutProps>) => utils.rerender(<Callout {...props} {...next} />),
  };
  return s;
}

describe('Callout', () => {
  test('dismiss-fires-on-dismiss', async () => {
    const s = setup({"dismissible": true});
    await s.user.click(activatable(s.dismissButton(), s.root()));
    expect(s.events.onDismiss).toHaveBeenCalled();
  });
  test('live-alert-renders-the-alert-role', async () => {
    const s = setup({"live": "alert"});
    expect(screen.getByRole('alert')).toBeInTheDocument();
  });
  test('live-status-renders-the-status-role', async () => {
    const s = setup({"live": "status"});
    expect(screen.getByRole('status')).toBeInTheDocument();
  });
  test('live-off-renders-no-role', async () => {
    const s = setup({"live": "off"});
    expect(s.container()).not.toHaveAttribute("role");
  });
  test('an-empty-heading-falls-back-to-the-body', async () => {
    const s = setup({"heading": "", "children": "Your card was declined."});
    expect(screen.getByText(new RegExp("Your\\ card\\ was\\ declined\\."))).toBeInTheDocument();
  });
  test('the-heading-is-rendered', async () => {
    const s = setup({"heading": "Payment failed"});
    expect(screen.getByText(new RegExp("Payment\\ failed"))).toBeInTheDocument();
  });
  test('renders', async () => {
    const s = setup({});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-info', async () => {
    const s = setup({"tone": "info"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-success', async () => {
    const s = setup({"tone": "success"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-warning', async () => {
    const s = setup({"tone": "warning"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-danger', async () => {
    const s = setup({"tone": "danger"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-status', async () => {
    const s = setup({"live": "status"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-alert', async () => {
    const s = setup({"live": "alert"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-off', async () => {
    const s = setup({"live": "off"});
    expect(s.root()).not.toBeNull();
  });
});
