// Generated by tools/behavior_tests.ts from the `behavior` block of the Callout doc. Do not edit.
import { describe, expect, test, vi } from 'vitest';
import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Callout } from '../src/Callout';
import type { CalloutProps } from '../src/Callout';
import meta from '../src/Callout.stories';

function setup(given: Partial<CalloutProps> = {}) {
  const events = {
    onDismiss: vi.fn(),
  };
  const props = { ...meta.args, ...given, onDismiss: events.onDismiss };
  const utils = render(<Callout {...props} />);
  const user = userEvent.setup();
  const s = {
    ...utils,
    user,
    events,
    props,
    root: () => (document.querySelector('[data-ds="Alert"]') ?? screen.queryByRole('status') ?? utils.container.firstElementChild) as HTMLElement,
    container: () => (screen.queryByRole('status') ?? s.root()) as HTMLElement,
    rerender: (next: Partial<CalloutProps>) => utils.rerender(<Callout {...props} {...next} />),
  };
  return s;
}

describe('Callout', () => {
  test('renders', async () => {
    const s = setup({});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-info', async () => {
    const s = setup({"tone": "info"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-success', async () => {
    const s = setup({"tone": "success"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-warning', async () => {
    const s = setup({"tone": "warning"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-tone-danger', async () => {
    const s = setup({"tone": "danger"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-status', async () => {
    const s = setup({"live": "status"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-alert', async () => {
    const s = setup({"live": "alert"});
    expect(s.root()).not.toBeNull();
  });
  test('renders-live-off', async () => {
    const s = setup({"live": "off"});
    expect(s.root()).not.toBeNull();
  });
});
