// Generated by tools/behavior_tests.ts from the `behavior` block of the Expander doc. Do not edit.
import { describe, expect, test, vi } from 'vitest';
import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Expander } from '../src/Expander';
import type { ExpanderProps } from '../src/Expander';
import meta from '../src/Expander.stories';

function setup(given: Partial<ExpanderProps> = {}) {
  const events = {
    onToggle: vi.fn(),
  };
  const props = { ...meta.args, ...given, onToggle: events.onToggle };
  const utils = render(<Expander {...props} />);
  const user = userEvent.setup();
  const s = {
    ...utils,
    user,
    events,
    props,
    root: () => (document.querySelector('[data-ds="Disclosure"]') ?? screen.queryByRole('button') ?? utils.container.firstElementChild) as HTMLElement,
    trigger: () => (screen.queryByRole('button') ?? s.root()) as HTMLElement,
    rerender: (next: Partial<ExpanderProps>) => utils.rerender(<Expander {...props} {...next} />),
  };
  return s;
}

describe('Expander', () => {
  test('renders', async () => {
    const s = setup({"open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-2', async () => {
    const s = setup({"headingLevel": "2", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-3', async () => {
    const s = setup({"headingLevel": "3", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-4', async () => {
    const s = setup({"headingLevel": "4", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-5', async () => {
    const s = setup({"headingLevel": "5", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-6', async () => {
    const s = setup({"headingLevel": "6", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('has-accessible-name', async () => {
    const s = setup({"open": true});
    expect(screen.getByRole('button', { name: s.props.summary })).toBeInTheDocument();
  });
  test('control-is-focusable', async () => {
    const s = setup({"open": true});
    act(() => (s.trigger()).focus());
    expect(s.trigger()).toHaveFocus();
  });
});
