// Generated by tools/behavior_tests.ts from the `behavior` block of the Expander doc. Do not edit.
import { describe, expect, test, vi } from 'vitest';
import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Expander } from '../src/Expander';
import type { ExpanderProps } from '../src/Expander';
import meta from '../src/Expander.stories';

const INTERACTIVE = "button, a[href], input:not([type=\"hidden\"]), select, textarea, [role=\"button\"], [role=\"checkbox\"], [role=\"switch\"], [role=\"radio\"], [role=\"textbox\"], [role=\"searchbox\"], [role=\"spinbutton\"], [role=\"combobox\"], [role=\"slider\"], [role=\"link\"], [role=\"tab\"], [role=\"menuitem\"], [role=\"menuitemcheckbox\"], [role=\"menuitemradio\"], [role=\"option\"], [role=\"treeitem\"], [role=\"scrollbar\"]";
const OWN_ROLE = "dialog, [role=\"dialog\"], [role=\"alertdialog\"], [role=\"combobox\"], [role=\"grid\"], [role=\"listbox\"], [role=\"menu\"], [role=\"menubar\"], [role=\"radiogroup\"], [role=\"tablist\"], [role=\"tree\"], [role=\"treegrid\"]";
function activatable(el: Element | null, root: Element | null): HTMLElement {
  if (el === null || el === root || el.matches(INTERACTIVE) || el.matches(OWN_ROLE)) return el as HTMLElement;
  return (el.querySelector(INTERACTIVE) ?? el) as HTMLElement;
}
function focusedPart(el: Element | null, root: Element | null): Element | null {
  return el === null || document.activeElement === el ? el : activatable(el, root);
}

function setup(given: Partial<ExpanderProps> = {}) {
  const events = {
    onToggle: vi.fn(),
  };
  const props = { ...meta.args, ...given, onToggle: events.onToggle };
  const utils = render(<Expander {...props} />);
  const user = userEvent.setup();
  const s = {
    ...utils,
    user,
    events,
    props,
    root: () => (document.querySelector('[data-ds="Disclosure"]') ?? screen.queryByRole('button') ?? utils.container.firstElementChild) as HTMLElement,
    trigger: () => (screen.queryByRole('button') ?? s.root()) as HTMLElement,
    rerender: (next: Partial<ExpanderProps>) => utils.rerender(<Expander {...props} {...next} />),
  };
  return s;
}

describe('Expander', () => {
  test('click-on-trigger-expands', async () => {
    const s = setup({"open": true});
    await s.user.click(activatable(s.trigger(), s.root()));
    expect(s.events.onToggle).toHaveBeenCalled();
    expect(s.trigger()).toHaveAttribute('aria-expanded', 'true');
  });
  test('open-disclosure-collapses-on-click', async () => {
    const s = setup({"defaultOpen": true, "open": true});
    await s.user.click(activatable(s.trigger(), s.root()));
    expect(s.events.onToggle).toHaveBeenCalled();
    expect(s.trigger()).toHaveAttribute('aria-expanded', 'false');
  });
  test('disabled-trigger-does-not-toggle', async () => {
    const s = setup({"disabled": true, "open": true});
    await userEvent.setup({ pointerEventsCheck: 0 }).click(activatable(s.trigger(), s.root()));
    expect(s.events.onToggle).not.toHaveBeenCalled();
    expect(s.trigger()).toHaveAttribute('aria-expanded', 'false');
    expect(s.trigger()).toHaveAttribute('aria-disabled', 'true');
  });
  test('disabled-trigger-stays-focusable', async () => {
    const s = setup({"disabled": true, "open": true});
    act(() => (s.trigger()).focus());
    expect(s.trigger()).toHaveFocus();
  });
  test('controlled-open-change-reports-controlled', async () => {
    const s = setup({"open": false});
    s.rerender({"open": true});
    expect(s.events.onToggle).toHaveBeenCalled();
    expect(s.trigger()).toHaveAttribute('aria-expanded', 'true');
  });
  test('renders', async () => {
    const s = setup({"open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-2', async () => {
    const s = setup({"headingLevel": "2", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-3', async () => {
    const s = setup({"headingLevel": "3", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-4', async () => {
    const s = setup({"headingLevel": "4", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-5', async () => {
    const s = setup({"headingLevel": "5", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('renders-heading-level-6', async () => {
    const s = setup({"headingLevel": "6", "open": true});
    expect(s.root()).not.toBeNull();
  });
  test('has-accessible-name', async () => {
    const s = setup({"open": true});
    expect(screen.getByRole('button', { name: s.props.summary })).toBeInTheDocument();
  });
  test('control-is-focusable', async () => {
    const s = setup({"open": true});
    act(() => (s.trigger()).focus());
    expect(s.trigger()).toHaveFocus();
  });
});
