/**
 * The site's navigation data, read from `generated/nav.json` at build time.
 *
 * `tools/site_nav.ts` writes that file from `generated/components.json` and `tools/regen-phases.json`
 * (the phase order), so the header's links and the docs sidebar's groups are generated, never
 * hand-maintained (site/src/content/docs/process/website-plan.md, "Content pipeline"). Read *in place*, like the
 * schema loader reads components.json — nothing is copied into this app.
 */
// Imported rather than read with node:fs so Vite resolves it relative to *this* file: a server
// module is bundled into dist/ before it runs, which moves `import.meta.url` out from under any
// relative path computed at runtime. nav.json is generated and gitignored, so a fresh clone must run
// `pnpm parse && pnpm nav` (see this app's README) or the build fails here with the path unresolved.
import navJson from '../../../generated/nav.json';

/** One top-level link. Mirrors `TopItem` in tools/site_nav.ts, which writes it. */
export type TopItem = { label: string; href: string; external?: true };
/** One component in a docs sidebar group. */
export type NavComponent = { name: string; slug: string };
/** One roadmap phase's worth of components, in the order the generator composes them. */
export type NavGroup = { phase: string; components: NavComponent[] };
export type Nav = { top: TopItem[]; docs: NavGroup[] };

/**
 * The docs sidebar's non-component destinations (website-plan.md, "Docs section": "Foundations
 * and Patterns get their own top-level `Link`s above the phase groups").
 *
 * Hand-written rather than generated, unlike everything else in this module: `generated/nav.json`
 * describes the 51 components grouped by phase, and tools/site_nav.ts's `top` list is the *site*
 * nav (Docs / GitHub / About; the logo is the home link). Neither has a section list, so the section routes live
 * here — one place both the sidebar and the mobile Select read them from.
 *
 * Naming demo joined them with job 523. It is a page about the components rather than one of them,
 * so it belongs beside Foundations and Patterns rather than in a phase group — and a comparison
 * nobody can find proves nothing, which is the whole point of that page.
 *
 * Spec sheet joined them when the two sections started rendering their Markdown. It is a Foundations
 * document like the other four, but a generated one — every token value and every style binding for
 * a whole theme, ten times the size of the rest of the folder — so it reads on a route of its own
 * (src/pages/docs/foundations/spec-sheet.astro) instead of inline on the section page, and a route
 * the navigation cannot reach is a page nobody finds. `OWN_PAGE_IDS` in
 * src/pages/docs/_prose.ts is where that split is decided; `FIXED_ROUTES` in tools/site_routes.ts is
 * the other hand-written half of this list and wants the same route, so the deploy gate checks it
 * was built.
 */
export const DOCS_SECTIONS: readonly TopItem[] = [
  { label: 'Foundations', href: '/docs/foundations' },
  { label: 'Spec sheet', href: '/docs/foundations/spec-sheet' },
  { label: 'Patterns', href: '/docs/patterns' },
  { label: 'Naming demo', href: '/docs/naming-demo' },
];

/** The route of one component's docs page. The one place that shape is written. */
export function componentRoute(slug: string): string {
  return `/docs/components/${slug}`;
}

/** The whole nav file, shape-checked. */
export function siteNav(): Nav {
  const parsed = navJson as Partial<Nav>;
  // A header with no links would build clean and ship broken, so the shape is checked here rather
  // than assumed: this is generated input, but it is generated by a tool that can regress.
  if (!Array.isArray(parsed.top) || parsed.top.length === 0) {
    throw new Error('generated/nav.json has no `top` links. Re-run `pnpm nav` at the repo root.');
  }
  if (!Array.isArray(parsed.docs)) {
    throw new Error('generated/nav.json has no `docs` groups. Re-run `pnpm nav` at the repo root.');
  }
  return { top: parsed.top, docs: parsed.docs };
}
