//  Icon+Paths.swift
//
//  GENERATED by `node --import tsx tools/icon-paths.ts` from tools/icon-paths.json — do not edit.
//  `pnpm icons:check` fails when this file and that table disagree.
//
//  The glyph table Icon draws from: one SVG path `d` per glyph name on a 16×16 grid, the same data the
//  web SVG uses, so a glyph beside a label looks the same on every platform. Support/SVGPath.swift turns a `d`
//  into a `Path`; `IconPaths.shape(_:)` is that `Path` as a `Shape` scaled to whatever square it is given.
//
//  Line glyphs stroke in the text color at `border.width.focus` (2 pt on the 16-grid) with round caps and
//  joins. The `filled` glyphs (info, success, warning, danger, ellipsis, play, pause) fill with fill-rule
//  even-odd and draw no stroke: each status shape's inner mark (i, check, !, x) is a hole, so it reads on any
//  surface without a second color.
//
//  Keyed by the doc's `name` value (`"chevron-right"`), not a Swift identifier, so the generated
//  `Icon.Name` enum can look its own `rawValue` up here and this file never has to know that type exists.

import SwiftUI

public enum IconPaths {
    /// The grid every `path` is drawn on. `shape(_:)` scales it to the square it is asked for.
    public static let grid: CGFloat = 16

    /// Stroke width for line glyphs, in points on the 16-grid (the `border.width.focus` token). Kept at this
    /// thickness at every rendered size, so glyphs stay legible at `xs`.
    public static let strokeWidth: CGFloat = 2

    /// Glyph name → path data on the 16-grid, and whether it fills (even-odd) rather than strokes.
    public static let table: [String: (path: String, filled: Bool)] = [
        "check":          (path: "M3 8.5l3.5 3.5L13 5", filled: false),
        "dash":           (path: "M4 8h8", filled: false),
        "chevron-right":  (path: "M6 3l5 5-5 5", filled: false),
        "chevron-down":   (path: "M3 6l5 5 5-5", filled: false),
        "chevron-up":     (path: "M3 10l5-5 5 5", filled: false),
        "chevron-left":   (path: "M10 3L5 8l5 5", filled: false),
        "close":          (path: "M3 3l10 10M13 3L3 13", filled: false),
        "plus":           (path: "M8 3v10M3 8h10", filled: false),
        "minus":          (path: "M3 8h10", filled: false),
        "info":           (path: "M8 1a7 7 0 1 0 0 14A7 7 0 1 0 8 1zm0 3a1 1 0 1 0 0 2 1 1 0 1 0 0-2zM7 7h2v4.5H7z", filled: true), // circle-i
        "success":        (path: "M8 1a7 7 0 1 0 0 14A7 7 0 1 0 8 1zM3.9 8.6 7 11.7l5.1-5.1-1.2-1.2L7 9.3 5.1 7.4z", filled: true), // circle-check
        "warning":        (path: "M8 1.5 15 14H1zM7 5.5h2V10H7zm1 5.5a1 1 0 1 0 0 2 1 1 0 1 0 0-2z", filled: true), // triangle-!
        "danger":         (path: "M5 1h6l4 4v6l-4 4H5l-4-4V5zm-.6 4.6 1.2-1.2L8 6.8l2.4-2.4 1.2 1.2L9.2 8l2.4 2.4-1.2 1.2L8 9.2l-2.4 2.4-1.2-1.2L6.8 8z", filled: true), // octagon-x
        "external":       (path: "M6 3H3v10h10v-3M9 3h4v4M13 3L7 9", filled: false),
        "ellipsis":       (path: "M1.75,8a1.25,1.25 0 1,0 2.5,0a1.25,1.25 0 1,0 -2.5,0M6.75,8a1.25,1.25 0 1,0 2.5,0a1.25,1.25 0 1,0 -2.5,0M11.75,8a1.25,1.25 0 1,0 2.5,0a1.25,1.25 0 1,0 -2.5,0", filled: true), // three dots, the web table's three r=1.25 circles as one path
        "search":         (path: "M7 2.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 1 0 0-9zM10.3 10.3L14 14", filled: false),
        "arrow-right":    (path: "M3 8h10M9 4l4 4-4 4", filled: false),
        "arrow-left":     (path: "M13 8H3M7 4L3 8l4 4", filled: false),
        "calendar":       (path: "M2.5 3.5h11v10h-11zM2.5 6.5h11M5.5 1.5v3M10.5 1.5v3", filled: false),
        "menu":           (path: "M2 4h12M2 8h12M2 12h12", filled: false),
        "list":           (path: "M5 4h9M5 8h9M5 12h9M2 4h.01M2 8h.01M2 12h.01", filled: false), // the bullet dots are zero-length round-capped strokes, so the whole glyph is one stroked path
        "grid":           (path: "M2 2h5v5H2zM9 2h5v5H9zM2 9h5v5H2zM9 9h5v5H9z", filled: false),
        "play":           (path: "M4 2l10 6-10 6z", filled: true),
        "pause":          (path: "M3 2h3v12H3zM10 2h3v12H10z", filled: true),
        "folder":         (path: "M2 13V2h5v2h7v9z", filled: false),
        "file":           (path: "M4 2h5l3 3v9H4zM9 2v3h3", filled: false),
    ]

    /// Every glyph name, in the order the Icon doc's `name` enum lists them.
    public static let names: [String] = [
        "check",
        "dash",
        "chevron-right",
        "chevron-down",
        "chevron-up",
        "chevron-left",
        "close",
        "plus",
        "minus",
        "info",
        "success",
        "warning",
        "danger",
        "external",
        "ellipsis",
        "search",
        "arrow-right",
        "arrow-left",
        "calendar",
        "menu",
        "list",
        "grid",
        "play",
        "pause",
        "folder",
        "file",
    ]

    /// The glyph for `name`, or nil when there is none — the caller decides whether that is a bug.
    public static func glyph(_ name: String) -> (path: String, filled: Bool)? {
        table[name]
    }

    /// The glyph as a `Shape`: the 16-grid path scaled to fit whatever rect it is laid out in, and centered
    /// there. Stroke it (line glyphs) or fill it with `FillStyle(eoFill: true)` (`filled` glyphs).
    public static func shape(_ name: String) -> SVGPathShape? {
        guard let glyph = table[name] else { return nil }
        return SVGPathShape(glyph.path, viewBox: CGSize(width: grid, height: grid))
    }
}
