//  Gallery+Generated.swift
//
//  Generated by tools/generate.ts after every swiftui generation round: one entry per
//  Sources/DesignSchema/Gallery+<Name>.swift. Do not edit by hand — the next generation overwrites it.

import SwiftUI

public extension Gallery {
    /// The generated component screens; `Gallery.entries` sorts them by name.
    static var generated: [GalleryEntry] {
        []
    }
}
