//  CalmPrecise.swift
//
//  Generated by tokens/build.mjs — do not edit; edit site/src/content/docs/themes/calm-precise.md and run `pnpm themes`.

import SwiftUI

public enum CalmPrecise {
    public static let definition = ThemeDefinition(
        id: "calm-precise",
        title: "Calm & precise",
        light: Light.table,
        dark: Dark.table
    )

    public enum Light {
        public static let colorPaletteNeutral0: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorPaletteNeutral50: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorPaletteNeutral100: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorPaletteNeutral200: Color = Color(red: 0.851, green: 0.8588, blue: 0.8667)
        public static let colorPaletteNeutral300: Color = Color(red: 0.7373, green: 0.7451, blue: 0.7569)
        public static let colorPaletteNeutral400: Color = Color(red: 0.5765, green: 0.5843, blue: 0.6)
        public static let colorPaletteNeutral500: Color = Color(red: 0.4392, green: 0.4431, blue: 0.4627)
        public static let colorPaletteNeutral600: Color = Color(red: 0.3373, green: 0.3451, blue: 0.3608)
        public static let colorPaletteNeutral700: Color = Color(red: 0.2549, green: 0.2588, blue: 0.2745)
        public static let colorPaletteNeutral800: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorPaletteNeutral900: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorPaletteNeutral1000: Color = Color(red: 0, green: 0, blue: 0)
        public static let colorPaletteBrand50: Color = Color(red: 0.9451, green: 0.9608, blue: 1)
        public static let colorPaletteBrand100: Color = Color(red: 0.8706, green: 0.9098, blue: 1)
        public static let colorPaletteBrand200: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorPaletteBrand300: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorPaletteBrand400: Color = Color(red: 0.4235, green: 0.5647, blue: 1)
        public static let colorPaletteBrand500: Color = Color(red: 0.2863, green: 0.4275, blue: 0.9294)
        public static let colorPaletteBrand600: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorPaletteBrand700: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorPaletteBrand800: Color = Color(red: 0.0863, green: 0.1373, blue: 0.5686)
        public static let colorPaletteBrand900: Color = Color(red: 0.0431, green: 0.0549, blue: 0.4235)
        public static let colorPaletteDanger50: Color = Color(red: 1, green: 0.949, blue: 0.9412)
        public static let colorPaletteDanger100: Color = Color(red: 1, green: 0.8745, blue: 0.8627)
        public static let colorPaletteDanger200: Color = Color(red: 1, green: 0.7647, blue: 0.7412)
        public static let colorPaletteDanger300: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorPaletteDanger400: Color = Color(red: 0.9608, green: 0.3765, blue: 0.3608)
        public static let colorPaletteDanger500: Color = Color(red: 0.8275, green: 0.2275, blue: 0.2353)
        public static let colorPaletteDanger600: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorPaletteDanger700: Color = Color(red: 0.5804, green: 0, blue: 0.0784)
        public static let colorPaletteDanger800: Color = Color(red: 0.4353, green: 0, blue: 0.0471)
        public static let colorPaletteDanger900: Color = Color(red: 0.298, green: 0, blue: 0.0196)
        public static let colorPaletteSuccess50: Color = Color(red: 0.8784, green: 1, blue: 0.8784)
        public static let colorPaletteSuccess100: Color = Color(red: 0.7451, green: 0.9804, blue: 0.7451)
        public static let colorPaletteSuccess200: Color = Color(red: 0.6275, green: 0.9176, blue: 0.6353)
        public static let colorPaletteSuccess300: Color = Color(red: 0.4627, green: 0.8157, blue: 0.4784)
        public static let colorPaletteSuccess400: Color = Color(red: 0.2902, green: 0.698, blue: 0.3255)
        public static let colorPaletteSuccess500: Color = Color(red: 0.1137, green: 0.5765, blue: 0.1882)
        public static let colorPaletteSuccess600: Color = Color(red: 0, green: 0.4745, blue: 0.1137)
        public static let colorPaletteSuccess700: Color = Color(red: 0, green: 0.3686, blue: 0.0784)
        public static let colorPaletteSuccess800: Color = Color(red: 0, green: 0.2706, blue: 0.0471)
        public static let colorPaletteSuccess900: Color = Color(red: 0, green: 0.1804, blue: 0.0196)
        public static let colorPaletteWarning50: Color = Color(red: 1, green: 0.9569, blue: 0.8824)
        public static let colorPaletteWarning100: Color = Color(red: 1, green: 0.8941, blue: 0.7176)
        public static let colorPaletteWarning200: Color = Color(red: 0.9882, green: 0.8, blue: 0.4706)
        public static let colorPaletteWarning300: Color = Color(red: 0.902, green: 0.6745, blue: 0.2471)
        public static let colorPaletteWarning400: Color = Color(red: 0.7725, green: 0.5529, blue: 0)
        public static let colorPaletteWarning500: Color = Color(red: 0.6235, green: 0.4431, blue: 0)
        public static let colorPaletteWarning600: Color = Color(red: 0.5098, green: 0.3569, blue: 0)
        public static let colorPaletteWarning700: Color = Color(red: 0.4, green: 0.2784, blue: 0)
        public static let colorPaletteWarning800: Color = Color(red: 0.2941, green: 0.2, blue: 0)
        public static let colorPaletteWarning900: Color = Color(red: 0.1961, green: 0.1255, blue: 0)
        public static let colorPaletteInfo50: Color = Color(red: 0.9451, green: 0.9608, blue: 1)
        public static let colorPaletteInfo100: Color = Color(red: 0.8706, green: 0.9098, blue: 1)
        public static let colorPaletteInfo200: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorPaletteInfo300: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorPaletteInfo400: Color = Color(red: 0.4471, green: 0.5765, blue: 0.9451)
        public static let colorPaletteInfo500: Color = Color(red: 0.3294, green: 0.451, blue: 0.8235)
        public static let colorPaletteInfo600: Color = Color(red: 0.251, green: 0.3569, blue: 0.7137)
        public static let colorPaletteInfo700: Color = Color(red: 0.1765, green: 0.2706, blue: 0.5922)
        public static let colorPaletteInfo800: Color = Color(red: 0.1176, green: 0.1882, blue: 0.4627)
        public static let colorPaletteInfo900: Color = Color(red: 0.0627, green: 0.1137, blue: 0.3255)
        public static let colorForeground: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorForegroundStrong: Color = Color(red: 0, green: 0, blue: 0)
        public static let colorForegroundMuted: Color = Color(red: 0.3373, green: 0.3451, blue: 0.3608)
        public static let colorForegroundOnAction: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorForegroundDanger: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorBackground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorBackgroundSubtle: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorBackgroundStrong: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorBorder: Color = Color(red: 0.851, green: 0.8588, blue: 0.8667)
        public static let colorBorderStrong: Color = Color(red: 0.5765, green: 0.5843, blue: 0.6)
        public static let colorBorderFocus: Color = Color(red: 0.2863, green: 0.4275, blue: 0.9294)
        public static let colorBorderDanger: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorLink: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorLinkHover: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorLinkVisited: Color = Color(red: 0.0863, green: 0.1373, blue: 0.5686)
        public static let colorControlBackground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorControlBorder: Color = Color(red: 0.5765, green: 0.5843, blue: 0.6)
        public static let colorControlSelectedBackground: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorControlSelectedForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorControlTrackOff: Color = Color(red: 0.5765, green: 0.5843, blue: 0.6)
        public static let colorStatusInfoBackground: Color = Color(red: 0.9451, green: 0.9608, blue: 1)
        public static let colorStatusInfoForeground: Color = Color(red: 0.251, green: 0.3569, blue: 0.7137)
        public static let colorStatusInfoBorder: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorStatusInfoIcon: Color = Color(red: 0.251, green: 0.3569, blue: 0.7137)
        public static let colorStatusSuccessBackground: Color = Color(red: 0.8784, green: 1, blue: 0.8784)
        public static let colorStatusSuccessForeground: Color = Color(red: 0, green: 0.4745, blue: 0.1137)
        public static let colorStatusSuccessBorder: Color = Color(red: 0.4627, green: 0.8157, blue: 0.4784)
        public static let colorStatusSuccessIcon: Color = Color(red: 0, green: 0.4745, blue: 0.1137)
        public static let colorStatusWarningBackground: Color = Color(red: 1, green: 0.9569, blue: 0.8824)
        public static let colorStatusWarningForeground: Color = Color(red: 0.5098, green: 0.3569, blue: 0)
        public static let colorStatusWarningBorder: Color = Color(red: 0.902, green: 0.6745, blue: 0.2471)
        public static let colorStatusWarningIcon: Color = Color(red: 0.5098, green: 0.3569, blue: 0)
        public static let colorStatusDangerBackground: Color = Color(red: 1, green: 0.949, blue: 0.9412)
        public static let colorStatusDangerForeground: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorStatusDangerBorder: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorStatusDangerIcon: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorOverlayScrim: Color = Color(red: 0, green: 0, blue: 0, opacity: 0.4)
        public static let colorOverlaySurface: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorInverseSurface: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorInverseForeground: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorInverseMuted: Color = Color(red: 0.7373, green: 0.7451, blue: 0.7569)
        public static let colorInverseLink: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorInverseFocus: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorInverseStatusNeutral: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorInverseStatusInfo: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorInverseStatusSuccess: Color = Color(red: 0.4627, green: 0.8157, blue: 0.4784)
        public static let colorInverseStatusWarning: Color = Color(red: 0.902, green: 0.6745, blue: 0.2471)
        public static let colorInverseStatusDanger: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorActionPrimaryBackground: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorActionPrimaryBackgroundHover: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorActionPrimaryForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorActionSecondaryBackground: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorActionSecondaryBackgroundHover: Color = Color(red: 0.851, green: 0.8588, blue: 0.8667)
        public static let colorActionSecondaryForeground: Color = Color(red: 0, green: 0, blue: 0)
        public static let colorActionGhostBackground: Color = Color.clear
        public static let colorActionGhostBackgroundHover: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorActionGhostForeground: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorActionDangerBackground: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorActionDangerBackgroundHover: Color = Color(red: 0.5804, green: 0, blue: 0.0784)
        public static let colorActionDangerForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let fontFamilyBody: FontFamilyToken = FontFamilyToken(design: .default)
        public static let fontFamilyHeading: FontFamilyToken = FontFamilyToken(design: .default)
        public static let fontFamilyMono: FontFamilyToken = FontFamilyToken(design: .monospaced)
        public static let fontWeightRegular: Font.Weight = .regular
        public static let fontWeightMedium: Font.Weight = .medium
        public static let fontWeightSemibold: Font.Weight = .semibold
        public static let fontWeightBold: Font.Weight = .bold
        public static let fontSizeXs: CGFloat = 11
        public static let fontSizeSm: CGFloat = 13
        public static let fontSizeMd: CGFloat = 16
        public static let fontSizeLg: CGFloat = 19
        public static let fontSizeXl: CGFloat = 23
        public static let fontSize2xl: CGFloat = 28
        public static let fontSize3xl: CGFloat = 33
        public static let fontSize4xl: CGFloat = 40
        public static let fontLineHeightTight: Double = 1.2
        public static let fontLineHeightNormal: Double = 1.5
        public static let fontLineHeightLoose: Double = 1.7
        public static let space0: CGFloat = 0
        public static let space1: CGFloat = 4
        public static let space2: CGFloat = 8
        public static let space3: CGFloat = 12
        public static let space4: CGFloat = 16
        public static let space5: CGFloat = 20
        public static let space6: CGFloat = 24
        public static let space8: CGFloat = 32
        public static let space10: CGFloat = 40
        public static let space12: CGFloat = 48
        public static let space16: CGFloat = 64
        public static let space20: CGFloat = 80
        public static let spaceSm: CGFloat = 8
        public static let spaceMd: CGFloat = 12
        public static let spaceLg: CGFloat = 16
        public static let layoutGutterNarrow: CGFloat = 16
        public static let layoutGutter: CGFloat = 24
        public static let layoutGutterWide: CGFloat = 32
        public static let layoutSectionSm: CGFloat = 32
        public static let layoutSectionMd: CGFloat = 48
        public static let layoutSectionLg: CGFloat = 64
        public static let layoutGapNone: CGFloat = 0
        public static let layoutGapTight: CGFloat = 4
        public static let layoutGapNormal: CGFloat = 8
        public static let layoutGapLoose: CGFloat = 16
        public static let layoutGapSection: CGFloat = 32
        public static let layoutInsetNone: CGFloat = 0
        public static let layoutInsetSm: CGFloat = 8
        public static let layoutInsetMd: CGFloat = 12
        public static let layoutInsetLg: CGFloat = 16
        public static let layoutInsetXl: CGFloat = 32
        public static let layoutMaxWidthProse: CGFloat = 572
        public static let layoutMaxWidthContent: CGFloat = 960
        public static let layoutMaxWidthPage: CGFloat = 1280
        public static let layoutBreakpointSm: CGFloat = 640
        public static let layoutBreakpointMd: CGFloat = 768
        public static let layoutBreakpointLg: CGFloat = 1024
        public static let sizeTargetMin: CGFloat = 24
        public static let sizeTargetComfortable: CGFloat = 44
        public static let radiusNone: CGFloat = 0
        public static let radiusSm: CGFloat = 2
        public static let radiusMd: CGFloat = 4
        public static let radiusLg: CGFloat = 6
        public static let radiusFull: CGFloat = 999
        public static let borderWidthThin: CGFloat = 1
        public static let borderWidthFocus: CGFloat = 2
        public static let opacityDisabled: Double = 0.5
        public static let layerBase: Double = 0
        public static let layerRaised: Double = 1
        public static let layerDropdown: Double = 100
        public static let layerSheet: Double = 200
        public static let layerDialog: Double = 300
        public static let layerToast: Double = 400
        public static let motionDurationFast: TimeInterval = 0.12
        public static let motionDurationBase: TimeInterval = 0.2
        public static let motionDurationLoop: TimeInterval = 0.8
        public static let motionEasingStandard: Animation = .timingCurve(0.2, 0, 0, 1)
        public static let motionEasingExit: Animation = .timingCurve(0.4, 0, 1, 1)
        public static let shadowRaised: ShadowToken = ShadowToken(color: Color(red: 0, green: 0, blue: 0, opacity: 0.102), x: 0, y: 1, blur: 3, spread: 0)
        public static let shadowOverlay: ShadowToken = ShadowToken(color: Color(red: 0, green: 0, blue: 0, opacity: 0.1804), x: 0, y: 8, blur: 24, spread: 0)

        private static let entries0: [(TokenRef, TokenValue)] = [
            (.colorPaletteNeutral0, .color(colorPaletteNeutral0)),
            (.colorPaletteNeutral50, .color(colorPaletteNeutral50)),
            (.colorPaletteNeutral100, .color(colorPaletteNeutral100)),
            (.colorPaletteNeutral200, .color(colorPaletteNeutral200)),
            (.colorPaletteNeutral300, .color(colorPaletteNeutral300)),
            (.colorPaletteNeutral400, .color(colorPaletteNeutral400)),
            (.colorPaletteNeutral500, .color(colorPaletteNeutral500)),
            (.colorPaletteNeutral600, .color(colorPaletteNeutral600)),
            (.colorPaletteNeutral700, .color(colorPaletteNeutral700)),
            (.colorPaletteNeutral800, .color(colorPaletteNeutral800)),
            (.colorPaletteNeutral900, .color(colorPaletteNeutral900)),
            (.colorPaletteNeutral1000, .color(colorPaletteNeutral1000)),
            (.colorPaletteBrand50, .color(colorPaletteBrand50)),
            (.colorPaletteBrand100, .color(colorPaletteBrand100)),
            (.colorPaletteBrand200, .color(colorPaletteBrand200)),
            (.colorPaletteBrand300, .color(colorPaletteBrand300)),
            (.colorPaletteBrand400, .color(colorPaletteBrand400)),
            (.colorPaletteBrand500, .color(colorPaletteBrand500)),
            (.colorPaletteBrand600, .color(colorPaletteBrand600)),
            (.colorPaletteBrand700, .color(colorPaletteBrand700)),
            (.colorPaletteBrand800, .color(colorPaletteBrand800)),
            (.colorPaletteBrand900, .color(colorPaletteBrand900)),
            (.colorPaletteDanger50, .color(colorPaletteDanger50)),
            (.colorPaletteDanger100, .color(colorPaletteDanger100)),
            (.colorPaletteDanger200, .color(colorPaletteDanger200)),
            (.colorPaletteDanger300, .color(colorPaletteDanger300)),
            (.colorPaletteDanger400, .color(colorPaletteDanger400)),
            (.colorPaletteDanger500, .color(colorPaletteDanger500)),
            (.colorPaletteDanger600, .color(colorPaletteDanger600)),
            (.colorPaletteDanger700, .color(colorPaletteDanger700)),
            (.colorPaletteDanger800, .color(colorPaletteDanger800)),
            (.colorPaletteDanger900, .color(colorPaletteDanger900)),
        ]

        private static let entries1: [(TokenRef, TokenValue)] = [
            (.colorPaletteSuccess50, .color(colorPaletteSuccess50)),
            (.colorPaletteSuccess100, .color(colorPaletteSuccess100)),
            (.colorPaletteSuccess200, .color(colorPaletteSuccess200)),
            (.colorPaletteSuccess300, .color(colorPaletteSuccess300)),
            (.colorPaletteSuccess400, .color(colorPaletteSuccess400)),
            (.colorPaletteSuccess500, .color(colorPaletteSuccess500)),
            (.colorPaletteSuccess600, .color(colorPaletteSuccess600)),
            (.colorPaletteSuccess700, .color(colorPaletteSuccess700)),
            (.colorPaletteSuccess800, .color(colorPaletteSuccess800)),
            (.colorPaletteSuccess900, .color(colorPaletteSuccess900)),
            (.colorPaletteWarning50, .color(colorPaletteWarning50)),
            (.colorPaletteWarning100, .color(colorPaletteWarning100)),
            (.colorPaletteWarning200, .color(colorPaletteWarning200)),
            (.colorPaletteWarning300, .color(colorPaletteWarning300)),
            (.colorPaletteWarning400, .color(colorPaletteWarning400)),
            (.colorPaletteWarning500, .color(colorPaletteWarning500)),
            (.colorPaletteWarning600, .color(colorPaletteWarning600)),
            (.colorPaletteWarning700, .color(colorPaletteWarning700)),
            (.colorPaletteWarning800, .color(colorPaletteWarning800)),
            (.colorPaletteWarning900, .color(colorPaletteWarning900)),
            (.colorPaletteInfo50, .color(colorPaletteInfo50)),
            (.colorPaletteInfo100, .color(colorPaletteInfo100)),
            (.colorPaletteInfo200, .color(colorPaletteInfo200)),
            (.colorPaletteInfo300, .color(colorPaletteInfo300)),
            (.colorPaletteInfo400, .color(colorPaletteInfo400)),
            (.colorPaletteInfo500, .color(colorPaletteInfo500)),
            (.colorPaletteInfo600, .color(colorPaletteInfo600)),
            (.colorPaletteInfo700, .color(colorPaletteInfo700)),
            (.colorPaletteInfo800, .color(colorPaletteInfo800)),
            (.colorPaletteInfo900, .color(colorPaletteInfo900)),
            (.colorForeground, .color(colorForeground)),
            (.colorForegroundStrong, .color(colorForegroundStrong)),
        ]

        private static let entries2: [(TokenRef, TokenValue)] = [
            (.colorForegroundMuted, .color(colorForegroundMuted)),
            (.colorForegroundOnAction, .color(colorForegroundOnAction)),
            (.colorForegroundDanger, .color(colorForegroundDanger)),
            (.colorBackground, .color(colorBackground)),
            (.colorBackgroundSubtle, .color(colorBackgroundSubtle)),
            (.colorBackgroundStrong, .color(colorBackgroundStrong)),
            (.colorBorder, .color(colorBorder)),
            (.colorBorderStrong, .color(colorBorderStrong)),
            (.colorBorderFocus, .color(colorBorderFocus)),
            (.colorBorderDanger, .color(colorBorderDanger)),
            (.colorLink, .color(colorLink)),
            (.colorLinkHover, .color(colorLinkHover)),
            (.colorLinkVisited, .color(colorLinkVisited)),
            (.colorControlBackground, .color(colorControlBackground)),
            (.colorControlBorder, .color(colorControlBorder)),
            (.colorControlSelectedBackground, .color(colorControlSelectedBackground)),
            (.colorControlSelectedForeground, .color(colorControlSelectedForeground)),
            (.colorControlTrackOff, .color(colorControlTrackOff)),
            (.colorStatusInfoBackground, .color(colorStatusInfoBackground)),
            (.colorStatusInfoForeground, .color(colorStatusInfoForeground)),
            (.colorStatusInfoBorder, .color(colorStatusInfoBorder)),
            (.colorStatusInfoIcon, .color(colorStatusInfoIcon)),
            (.colorStatusSuccessBackground, .color(colorStatusSuccessBackground)),
            (.colorStatusSuccessForeground, .color(colorStatusSuccessForeground)),
            (.colorStatusSuccessBorder, .color(colorStatusSuccessBorder)),
            (.colorStatusSuccessIcon, .color(colorStatusSuccessIcon)),
            (.colorStatusWarningBackground, .color(colorStatusWarningBackground)),
            (.colorStatusWarningForeground, .color(colorStatusWarningForeground)),
            (.colorStatusWarningBorder, .color(colorStatusWarningBorder)),
            (.colorStatusWarningIcon, .color(colorStatusWarningIcon)),
            (.colorStatusDangerBackground, .color(colorStatusDangerBackground)),
            (.colorStatusDangerForeground, .color(colorStatusDangerForeground)),
        ]

        private static let entries3: [(TokenRef, TokenValue)] = [
            (.colorStatusDangerBorder, .color(colorStatusDangerBorder)),
            (.colorStatusDangerIcon, .color(colorStatusDangerIcon)),
            (.colorOverlayScrim, .color(colorOverlayScrim)),
            (.colorOverlaySurface, .color(colorOverlaySurface)),
            (.colorInverseSurface, .color(colorInverseSurface)),
            (.colorInverseForeground, .color(colorInverseForeground)),
            (.colorInverseMuted, .color(colorInverseMuted)),
            (.colorInverseLink, .color(colorInverseLink)),
            (.colorInverseFocus, .color(colorInverseFocus)),
            (.colorInverseStatusNeutral, .color(colorInverseStatusNeutral)),
            (.colorInverseStatusInfo, .color(colorInverseStatusInfo)),
            (.colorInverseStatusSuccess, .color(colorInverseStatusSuccess)),
            (.colorInverseStatusWarning, .color(colorInverseStatusWarning)),
            (.colorInverseStatusDanger, .color(colorInverseStatusDanger)),
            (.colorActionPrimaryBackground, .color(colorActionPrimaryBackground)),
            (.colorActionPrimaryBackgroundHover, .color(colorActionPrimaryBackgroundHover)),
            (.colorActionPrimaryForeground, .color(colorActionPrimaryForeground)),
            (.colorActionSecondaryBackground, .color(colorActionSecondaryBackground)),
            (.colorActionSecondaryBackgroundHover, .color(colorActionSecondaryBackgroundHover)),
            (.colorActionSecondaryForeground, .color(colorActionSecondaryForeground)),
            (.colorActionGhostBackground, .color(colorActionGhostBackground)),
            (.colorActionGhostBackgroundHover, .color(colorActionGhostBackgroundHover)),
            (.colorActionGhostForeground, .color(colorActionGhostForeground)),
            (.colorActionDangerBackground, .color(colorActionDangerBackground)),
            (.colorActionDangerBackgroundHover, .color(colorActionDangerBackgroundHover)),
            (.colorActionDangerForeground, .color(colorActionDangerForeground)),
            (.fontFamilyBody, .fontFamily(fontFamilyBody)),
            (.fontFamilyHeading, .fontFamily(fontFamilyHeading)),
            (.fontFamilyMono, .fontFamily(fontFamilyMono)),
            (.fontWeightRegular, .fontWeight(fontWeightRegular)),
            (.fontWeightMedium, .fontWeight(fontWeightMedium)),
            (.fontWeightSemibold, .fontWeight(fontWeightSemibold)),
        ]

        private static let entries4: [(TokenRef, TokenValue)] = [
            (.fontWeightBold, .fontWeight(fontWeightBold)),
            (.fontSizeXs, .dimension(fontSizeXs)),
            (.fontSizeSm, .dimension(fontSizeSm)),
            (.fontSizeMd, .dimension(fontSizeMd)),
            (.fontSizeLg, .dimension(fontSizeLg)),
            (.fontSizeXl, .dimension(fontSizeXl)),
            (.fontSize2xl, .dimension(fontSize2xl)),
            (.fontSize3xl, .dimension(fontSize3xl)),
            (.fontSize4xl, .dimension(fontSize4xl)),
            (.fontLineHeightTight, .number(fontLineHeightTight)),
            (.fontLineHeightNormal, .number(fontLineHeightNormal)),
            (.fontLineHeightLoose, .number(fontLineHeightLoose)),
            (.space0, .dimension(space0)),
            (.space1, .dimension(space1)),
            (.space2, .dimension(space2)),
            (.space3, .dimension(space3)),
            (.space4, .dimension(space4)),
            (.space5, .dimension(space5)),
            (.space6, .dimension(space6)),
            (.space8, .dimension(space8)),
            (.space10, .dimension(space10)),
            (.space12, .dimension(space12)),
            (.space16, .dimension(space16)),
            (.space20, .dimension(space20)),
            (.spaceSm, .dimension(spaceSm)),
            (.spaceMd, .dimension(spaceMd)),
            (.spaceLg, .dimension(spaceLg)),
            (.layoutGutterNarrow, .dimension(layoutGutterNarrow)),
            (.layoutGutter, .dimension(layoutGutter)),
            (.layoutGutterWide, .dimension(layoutGutterWide)),
            (.layoutSectionSm, .dimension(layoutSectionSm)),
            (.layoutSectionMd, .dimension(layoutSectionMd)),
        ]

        private static let entries5: [(TokenRef, TokenValue)] = [
            (.layoutSectionLg, .dimension(layoutSectionLg)),
            (.layoutGapNone, .dimension(layoutGapNone)),
            (.layoutGapTight, .dimension(layoutGapTight)),
            (.layoutGapNormal, .dimension(layoutGapNormal)),
            (.layoutGapLoose, .dimension(layoutGapLoose)),
            (.layoutGapSection, .dimension(layoutGapSection)),
            (.layoutInsetNone, .dimension(layoutInsetNone)),
            (.layoutInsetSm, .dimension(layoutInsetSm)),
            (.layoutInsetMd, .dimension(layoutInsetMd)),
            (.layoutInsetLg, .dimension(layoutInsetLg)),
            (.layoutInsetXl, .dimension(layoutInsetXl)),
            (.layoutMaxWidthProse, .dimension(layoutMaxWidthProse)),
            (.layoutMaxWidthContent, .dimension(layoutMaxWidthContent)),
            (.layoutMaxWidthPage, .dimension(layoutMaxWidthPage)),
            (.layoutBreakpointSm, .dimension(layoutBreakpointSm)),
            (.layoutBreakpointMd, .dimension(layoutBreakpointMd)),
            (.layoutBreakpointLg, .dimension(layoutBreakpointLg)),
            (.sizeTargetMin, .dimension(sizeTargetMin)),
            (.sizeTargetComfortable, .dimension(sizeTargetComfortable)),
            (.radiusNone, .dimension(radiusNone)),
            (.radiusSm, .dimension(radiusSm)),
            (.radiusMd, .dimension(radiusMd)),
            (.radiusLg, .dimension(radiusLg)),
            (.radiusFull, .dimension(radiusFull)),
            (.borderWidthThin, .dimension(borderWidthThin)),
            (.borderWidthFocus, .dimension(borderWidthFocus)),
            (.opacityDisabled, .number(opacityDisabled)),
            (.layerBase, .number(layerBase)),
            (.layerRaised, .number(layerRaised)),
            (.layerDropdown, .number(layerDropdown)),
            (.layerSheet, .number(layerSheet)),
            (.layerDialog, .number(layerDialog)),
        ]

        private static let entries6: [(TokenRef, TokenValue)] = [
            (.layerToast, .number(layerToast)),
            (.motionDurationFast, .duration(motionDurationFast)),
            (.motionDurationBase, .duration(motionDurationBase)),
            (.motionDurationLoop, .duration(motionDurationLoop)),
            (.motionEasingStandard, .animation(motionEasingStandard)),
            (.motionEasingExit, .animation(motionEasingExit)),
            (.shadowRaised, .shadow(shadowRaised)),
            (.shadowOverlay, .shadow(shadowOverlay)),
        ]

        public static let table = TokenTable(Dictionary(uniqueKeysWithValues: [entries0, entries1, entries2, entries3, entries4, entries5, entries6].joined()))
    }

    public enum Dark {
        public static let colorPaletteNeutral0: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorPaletteNeutral50: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9725)
        public static let colorPaletteNeutral100: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorPaletteNeutral200: Color = Color(red: 0.851, green: 0.8588, blue: 0.8667)
        public static let colorPaletteNeutral300: Color = Color(red: 0.7373, green: 0.7451, blue: 0.7569)
        public static let colorPaletteNeutral400: Color = Color(red: 0.5765, green: 0.5843, blue: 0.6)
        public static let colorPaletteNeutral500: Color = Color(red: 0.4392, green: 0.4431, blue: 0.4627)
        public static let colorPaletteNeutral600: Color = Color(red: 0.3373, green: 0.3451, blue: 0.3608)
        public static let colorPaletteNeutral700: Color = Color(red: 0.2549, green: 0.2588, blue: 0.2745)
        public static let colorPaletteNeutral800: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorPaletteNeutral900: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorPaletteNeutral1000: Color = Color(red: 0, green: 0, blue: 0)
        public static let colorPaletteBrand50: Color = Color(red: 0.9451, green: 0.9608, blue: 1)
        public static let colorPaletteBrand100: Color = Color(red: 0.8706, green: 0.9098, blue: 1)
        public static let colorPaletteBrand200: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorPaletteBrand300: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorPaletteBrand400: Color = Color(red: 0.4235, green: 0.5647, blue: 1)
        public static let colorPaletteBrand500: Color = Color(red: 0.2863, green: 0.4275, blue: 0.9294)
        public static let colorPaletteBrand600: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorPaletteBrand700: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorPaletteBrand800: Color = Color(red: 0.0863, green: 0.1373, blue: 0.5686)
        public static let colorPaletteBrand900: Color = Color(red: 0.0431, green: 0.0549, blue: 0.4235)
        public static let colorPaletteDanger50: Color = Color(red: 1, green: 0.949, blue: 0.9412)
        public static let colorPaletteDanger100: Color = Color(red: 1, green: 0.8745, blue: 0.8627)
        public static let colorPaletteDanger200: Color = Color(red: 1, green: 0.7647, blue: 0.7412)
        public static let colorPaletteDanger300: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorPaletteDanger400: Color = Color(red: 0.9608, green: 0.3765, blue: 0.3608)
        public static let colorPaletteDanger500: Color = Color(red: 0.8275, green: 0.2275, blue: 0.2353)
        public static let colorPaletteDanger600: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorPaletteDanger700: Color = Color(red: 0.5804, green: 0, blue: 0.0784)
        public static let colorPaletteDanger800: Color = Color(red: 0.4353, green: 0, blue: 0.0471)
        public static let colorPaletteDanger900: Color = Color(red: 0.298, green: 0, blue: 0.0196)
        public static let colorPaletteSuccess50: Color = Color(red: 0.8784, green: 1, blue: 0.8784)
        public static let colorPaletteSuccess100: Color = Color(red: 0.7451, green: 0.9804, blue: 0.7451)
        public static let colorPaletteSuccess200: Color = Color(red: 0.6275, green: 0.9176, blue: 0.6353)
        public static let colorPaletteSuccess300: Color = Color(red: 0.4627, green: 0.8157, blue: 0.4784)
        public static let colorPaletteSuccess400: Color = Color(red: 0.2902, green: 0.698, blue: 0.3255)
        public static let colorPaletteSuccess500: Color = Color(red: 0.1137, green: 0.5765, blue: 0.1882)
        public static let colorPaletteSuccess600: Color = Color(red: 0, green: 0.4745, blue: 0.1137)
        public static let colorPaletteSuccess700: Color = Color(red: 0, green: 0.3686, blue: 0.0784)
        public static let colorPaletteSuccess800: Color = Color(red: 0, green: 0.2706, blue: 0.0471)
        public static let colorPaletteSuccess900: Color = Color(red: 0, green: 0.1804, blue: 0.0196)
        public static let colorPaletteWarning50: Color = Color(red: 1, green: 0.9569, blue: 0.8824)
        public static let colorPaletteWarning100: Color = Color(red: 1, green: 0.8941, blue: 0.7176)
        public static let colorPaletteWarning200: Color = Color(red: 0.9882, green: 0.8, blue: 0.4706)
        public static let colorPaletteWarning300: Color = Color(red: 0.902, green: 0.6745, blue: 0.2471)
        public static let colorPaletteWarning400: Color = Color(red: 0.7725, green: 0.5529, blue: 0)
        public static let colorPaletteWarning500: Color = Color(red: 0.6235, green: 0.4431, blue: 0)
        public static let colorPaletteWarning600: Color = Color(red: 0.5098, green: 0.3569, blue: 0)
        public static let colorPaletteWarning700: Color = Color(red: 0.4, green: 0.2784, blue: 0)
        public static let colorPaletteWarning800: Color = Color(red: 0.2941, green: 0.2, blue: 0)
        public static let colorPaletteWarning900: Color = Color(red: 0.1961, green: 0.1255, blue: 0)
        public static let colorPaletteInfo50: Color = Color(red: 0.9451, green: 0.9608, blue: 1)
        public static let colorPaletteInfo100: Color = Color(red: 0.8706, green: 0.9098, blue: 1)
        public static let colorPaletteInfo200: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorPaletteInfo300: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorPaletteInfo400: Color = Color(red: 0.4471, green: 0.5765, blue: 0.9451)
        public static let colorPaletteInfo500: Color = Color(red: 0.3294, green: 0.451, blue: 0.8235)
        public static let colorPaletteInfo600: Color = Color(red: 0.251, green: 0.3569, blue: 0.7137)
        public static let colorPaletteInfo700: Color = Color(red: 0.1765, green: 0.2706, blue: 0.5922)
        public static let colorPaletteInfo800: Color = Color(red: 0.1176, green: 0.1882, blue: 0.4627)
        public static let colorPaletteInfo900: Color = Color(red: 0.0627, green: 0.1137, blue: 0.3255)
        public static let colorForeground: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorForegroundStrong: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorForegroundMuted: Color = Color(red: 0.7373, green: 0.7451, blue: 0.7569)
        public static let colorForegroundOnAction: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorForegroundDanger: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorBackground: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorBackgroundSubtle: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorBackgroundStrong: Color = Color(red: 0.2549, green: 0.2588, blue: 0.2745)
        public static let colorBorder: Color = Color(red: 0.2549, green: 0.2588, blue: 0.2745)
        public static let colorBorderStrong: Color = Color(red: 0.4392, green: 0.4431, blue: 0.4627)
        public static let colorBorderFocus: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorBorderDanger: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorLink: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorLinkHover: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorLinkVisited: Color = Color(red: 0.8706, green: 0.9098, blue: 1)
        public static let colorControlBackground: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorControlBorder: Color = Color(red: 0.4392, green: 0.4431, blue: 0.4627)
        public static let colorControlSelectedBackground: Color = Color(red: 0.2863, green: 0.4275, blue: 0.9294)
        public static let colorControlSelectedForeground: Color = Color(red: 0, green: 0, blue: 0)
        public static let colorControlTrackOff: Color = Color(red: 0.4392, green: 0.4431, blue: 0.4627)
        public static let colorStatusInfoBackground: Color = Color(red: 0.0627, green: 0.1137, blue: 0.3255)
        public static let colorStatusInfoForeground: Color = Color(red: 0.7608, green: 0.8314, blue: 1)
        public static let colorStatusInfoBorder: Color = Color(red: 0.1765, green: 0.2706, blue: 0.5922)
        public static let colorStatusInfoIcon: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorStatusSuccessBackground: Color = Color(red: 0, green: 0.1804, blue: 0.0196)
        public static let colorStatusSuccessForeground: Color = Color(red: 0.6275, green: 0.9176, blue: 0.6353)
        public static let colorStatusSuccessBorder: Color = Color(red: 0, green: 0.3686, blue: 0.0784)
        public static let colorStatusSuccessIcon: Color = Color(red: 0.4627, green: 0.8157, blue: 0.4784)
        public static let colorStatusWarningBackground: Color = Color(red: 0.1961, green: 0.1255, blue: 0)
        public static let colorStatusWarningForeground: Color = Color(red: 0.9882, green: 0.8, blue: 0.4706)
        public static let colorStatusWarningBorder: Color = Color(red: 0.4, green: 0.2784, blue: 0)
        public static let colorStatusWarningIcon: Color = Color(red: 0.902, green: 0.6745, blue: 0.2471)
        public static let colorStatusDangerBackground: Color = Color(red: 0.298, green: 0, blue: 0.0196)
        public static let colorStatusDangerForeground: Color = Color(red: 1, green: 0.7647, blue: 0.7412)
        public static let colorStatusDangerBorder: Color = Color(red: 0.5804, green: 0, blue: 0.0784)
        public static let colorStatusDangerIcon: Color = Color(red: 1, green: 0.5843, blue: 0.5529)
        public static let colorOverlayScrim: Color = Color(red: 0, green: 0, blue: 0, opacity: 0.6)
        public static let colorOverlaySurface: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorInverseSurface: Color = Color(red: 0.9255, green: 0.9294, blue: 0.9333)
        public static let colorInverseForeground: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorInverseMuted: Color = Color(red: 0.3373, green: 0.3451, blue: 0.3608)
        public static let colorInverseLink: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorInverseFocus: Color = Color(red: 0.1412, green: 0.2275, blue: 0.702)
        public static let colorInverseStatusNeutral: Color = Color(red: 0.0902, green: 0.0941, blue: 0.1059)
        public static let colorInverseStatusInfo: Color = Color(red: 0.251, green: 0.3569, blue: 0.7137)
        public static let colorInverseStatusSuccess: Color = Color(red: 0, green: 0.4745, blue: 0.1137)
        public static let colorInverseStatusWarning: Color = Color(red: 0.5098, green: 0.3569, blue: 0)
        public static let colorInverseStatusDanger: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorActionPrimaryBackground: Color = Color(red: 0.2078, green: 0.3255, blue: 0.8235)
        public static let colorActionPrimaryBackgroundHover: Color = Color(red: 0.2863, green: 0.4275, blue: 0.9294)
        public static let colorActionPrimaryForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorActionSecondaryBackground: Color = Color(red: 0.2549, green: 0.2588, blue: 0.2745)
        public static let colorActionSecondaryBackgroundHover: Color = Color(red: 0.3373, green: 0.3451, blue: 0.3608)
        public static let colorActionSecondaryForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let colorActionGhostBackground: Color = Color.clear
        public static let colorActionGhostBackgroundHover: Color = Color(red: 0.1647, green: 0.1686, blue: 0.1843)
        public static let colorActionGhostForeground: Color = Color(red: 0.6, green: 0.7098, blue: 1)
        public static let colorActionDangerBackground: Color = Color(red: 0.8275, green: 0.2275, blue: 0.2353)
        public static let colorActionDangerBackgroundHover: Color = Color(red: 0.7098, green: 0.1137, blue: 0.149)
        public static let colorActionDangerForeground: Color = Color(red: 1, green: 1, blue: 1)
        public static let fontFamilyBody: FontFamilyToken = FontFamilyToken(design: .default)
        public static let fontFamilyHeading: FontFamilyToken = FontFamilyToken(design: .default)
        public static let fontFamilyMono: FontFamilyToken = FontFamilyToken(design: .monospaced)
        public static let fontWeightRegular: Font.Weight = .regular
        public static let fontWeightMedium: Font.Weight = .medium
        public static let fontWeightSemibold: Font.Weight = .semibold
        public static let fontWeightBold: Font.Weight = .bold
        public static let fontSizeXs: CGFloat = 11
        public static let fontSizeSm: CGFloat = 13
        public static let fontSizeMd: CGFloat = 16
        public static let fontSizeLg: CGFloat = 19
        public static let fontSizeXl: CGFloat = 23
        public static let fontSize2xl: CGFloat = 28
        public static let fontSize3xl: CGFloat = 33
        public static let fontSize4xl: CGFloat = 40
        public static let fontLineHeightTight: Double = 1.2
        public static let fontLineHeightNormal: Double = 1.5
        public static let fontLineHeightLoose: Double = 1.7
        public static let space0: CGFloat = 0
        public static let space1: CGFloat = 4
        public static let space2: CGFloat = 8
        public static let space3: CGFloat = 12
        public static let space4: CGFloat = 16
        public static let space5: CGFloat = 20
        public static let space6: CGFloat = 24
        public static let space8: CGFloat = 32
        public static let space10: CGFloat = 40
        public static let space12: CGFloat = 48
        public static let space16: CGFloat = 64
        public static let space20: CGFloat = 80
        public static let spaceSm: CGFloat = 8
        public static let spaceMd: CGFloat = 12
        public static let spaceLg: CGFloat = 16
        public static let layoutGutterNarrow: CGFloat = 16
        public static let layoutGutter: CGFloat = 24
        public static let layoutGutterWide: CGFloat = 32
        public static let layoutSectionSm: CGFloat = 32
        public static let layoutSectionMd: CGFloat = 48
        public static let layoutSectionLg: CGFloat = 64
        public static let layoutGapNone: CGFloat = 0
        public static let layoutGapTight: CGFloat = 4
        public static let layoutGapNormal: CGFloat = 8
        public static let layoutGapLoose: CGFloat = 16
        public static let layoutGapSection: CGFloat = 32
        public static let layoutInsetNone: CGFloat = 0
        public static let layoutInsetSm: CGFloat = 8
        public static let layoutInsetMd: CGFloat = 12
        public static let layoutInsetLg: CGFloat = 16
        public static let layoutInsetXl: CGFloat = 32
        public static let layoutMaxWidthProse: CGFloat = 572
        public static let layoutMaxWidthContent: CGFloat = 960
        public static let layoutMaxWidthPage: CGFloat = 1280
        public static let layoutBreakpointSm: CGFloat = 640
        public static let layoutBreakpointMd: CGFloat = 768
        public static let layoutBreakpointLg: CGFloat = 1024
        public static let sizeTargetMin: CGFloat = 24
        public static let sizeTargetComfortable: CGFloat = 44
        public static let radiusNone: CGFloat = 0
        public static let radiusSm: CGFloat = 2
        public static let radiusMd: CGFloat = 4
        public static let radiusLg: CGFloat = 6
        public static let radiusFull: CGFloat = 999
        public static let borderWidthThin: CGFloat = 1
        public static let borderWidthFocus: CGFloat = 2
        public static let opacityDisabled: Double = 0.5
        public static let layerBase: Double = 0
        public static let layerRaised: Double = 1
        public static let layerDropdown: Double = 100
        public static let layerSheet: Double = 200
        public static let layerDialog: Double = 300
        public static let layerToast: Double = 400
        public static let motionDurationFast: TimeInterval = 0.12
        public static let motionDurationBase: TimeInterval = 0.2
        public static let motionDurationLoop: TimeInterval = 0.8
        public static let motionEasingStandard: Animation = .timingCurve(0.2, 0, 0, 1)
        public static let motionEasingExit: Animation = .timingCurve(0.4, 0, 1, 1)
        public static let shadowRaised: ShadowToken = ShadowToken(color: Color(red: 0, green: 0, blue: 0, opacity: 0.349), x: 0, y: 1, blur: 3, spread: 0)
        public static let shadowOverlay: ShadowToken = ShadowToken(color: Color(red: 0, green: 0, blue: 0, opacity: 0.502), x: 0, y: 8, blur: 24, spread: 0)

        private static let entries0: [(TokenRef, TokenValue)] = [
            (.colorPaletteNeutral0, .color(colorPaletteNeutral0)),
            (.colorPaletteNeutral50, .color(colorPaletteNeutral50)),
            (.colorPaletteNeutral100, .color(colorPaletteNeutral100)),
            (.colorPaletteNeutral200, .color(colorPaletteNeutral200)),
            (.colorPaletteNeutral300, .color(colorPaletteNeutral300)),
            (.colorPaletteNeutral400, .color(colorPaletteNeutral400)),
            (.colorPaletteNeutral500, .color(colorPaletteNeutral500)),
            (.colorPaletteNeutral600, .color(colorPaletteNeutral600)),
            (.colorPaletteNeutral700, .color(colorPaletteNeutral700)),
            (.colorPaletteNeutral800, .color(colorPaletteNeutral800)),
            (.colorPaletteNeutral900, .color(colorPaletteNeutral900)),
            (.colorPaletteNeutral1000, .color(colorPaletteNeutral1000)),
            (.colorPaletteBrand50, .color(colorPaletteBrand50)),
            (.colorPaletteBrand100, .color(colorPaletteBrand100)),
            (.colorPaletteBrand200, .color(colorPaletteBrand200)),
            (.colorPaletteBrand300, .color(colorPaletteBrand300)),
            (.colorPaletteBrand400, .color(colorPaletteBrand400)),
            (.colorPaletteBrand500, .color(colorPaletteBrand500)),
            (.colorPaletteBrand600, .color(colorPaletteBrand600)),
            (.colorPaletteBrand700, .color(colorPaletteBrand700)),
            (.colorPaletteBrand800, .color(colorPaletteBrand800)),
            (.colorPaletteBrand900, .color(colorPaletteBrand900)),
            (.colorPaletteDanger50, .color(colorPaletteDanger50)),
            (.colorPaletteDanger100, .color(colorPaletteDanger100)),
            (.colorPaletteDanger200, .color(colorPaletteDanger200)),
            (.colorPaletteDanger300, .color(colorPaletteDanger300)),
            (.colorPaletteDanger400, .color(colorPaletteDanger400)),
            (.colorPaletteDanger500, .color(colorPaletteDanger500)),
            (.colorPaletteDanger600, .color(colorPaletteDanger600)),
            (.colorPaletteDanger700, .color(colorPaletteDanger700)),
            (.colorPaletteDanger800, .color(colorPaletteDanger800)),
            (.colorPaletteDanger900, .color(colorPaletteDanger900)),
        ]

        private static let entries1: [(TokenRef, TokenValue)] = [
            (.colorPaletteSuccess50, .color(colorPaletteSuccess50)),
            (.colorPaletteSuccess100, .color(colorPaletteSuccess100)),
            (.colorPaletteSuccess200, .color(colorPaletteSuccess200)),
            (.colorPaletteSuccess300, .color(colorPaletteSuccess300)),
            (.colorPaletteSuccess400, .color(colorPaletteSuccess400)),
            (.colorPaletteSuccess500, .color(colorPaletteSuccess500)),
            (.colorPaletteSuccess600, .color(colorPaletteSuccess600)),
            (.colorPaletteSuccess700, .color(colorPaletteSuccess700)),
            (.colorPaletteSuccess800, .color(colorPaletteSuccess800)),
            (.colorPaletteSuccess900, .color(colorPaletteSuccess900)),
            (.colorPaletteWarning50, .color(colorPaletteWarning50)),
            (.colorPaletteWarning100, .color(colorPaletteWarning100)),
            (.colorPaletteWarning200, .color(colorPaletteWarning200)),
            (.colorPaletteWarning300, .color(colorPaletteWarning300)),
            (.colorPaletteWarning400, .color(colorPaletteWarning400)),
            (.colorPaletteWarning500, .color(colorPaletteWarning500)),
            (.colorPaletteWarning600, .color(colorPaletteWarning600)),
            (.colorPaletteWarning700, .color(colorPaletteWarning700)),
            (.colorPaletteWarning800, .color(colorPaletteWarning800)),
            (.colorPaletteWarning900, .color(colorPaletteWarning900)),
            (.colorPaletteInfo50, .color(colorPaletteInfo50)),
            (.colorPaletteInfo100, .color(colorPaletteInfo100)),
            (.colorPaletteInfo200, .color(colorPaletteInfo200)),
            (.colorPaletteInfo300, .color(colorPaletteInfo300)),
            (.colorPaletteInfo400, .color(colorPaletteInfo400)),
            (.colorPaletteInfo500, .color(colorPaletteInfo500)),
            (.colorPaletteInfo600, .color(colorPaletteInfo600)),
            (.colorPaletteInfo700, .color(colorPaletteInfo700)),
            (.colorPaletteInfo800, .color(colorPaletteInfo800)),
            (.colorPaletteInfo900, .color(colorPaletteInfo900)),
            (.colorForeground, .color(colorForeground)),
            (.colorForegroundStrong, .color(colorForegroundStrong)),
        ]

        private static let entries2: [(TokenRef, TokenValue)] = [
            (.colorForegroundMuted, .color(colorForegroundMuted)),
            (.colorForegroundOnAction, .color(colorForegroundOnAction)),
            (.colorForegroundDanger, .color(colorForegroundDanger)),
            (.colorBackground, .color(colorBackground)),
            (.colorBackgroundSubtle, .color(colorBackgroundSubtle)),
            (.colorBackgroundStrong, .color(colorBackgroundStrong)),
            (.colorBorder, .color(colorBorder)),
            (.colorBorderStrong, .color(colorBorderStrong)),
            (.colorBorderFocus, .color(colorBorderFocus)),
            (.colorBorderDanger, .color(colorBorderDanger)),
            (.colorLink, .color(colorLink)),
            (.colorLinkHover, .color(colorLinkHover)),
            (.colorLinkVisited, .color(colorLinkVisited)),
            (.colorControlBackground, .color(colorControlBackground)),
            (.colorControlBorder, .color(colorControlBorder)),
            (.colorControlSelectedBackground, .color(colorControlSelectedBackground)),
            (.colorControlSelectedForeground, .color(colorControlSelectedForeground)),
            (.colorControlTrackOff, .color(colorControlTrackOff)),
            (.colorStatusInfoBackground, .color(colorStatusInfoBackground)),
            (.colorStatusInfoForeground, .color(colorStatusInfoForeground)),
            (.colorStatusInfoBorder, .color(colorStatusInfoBorder)),
            (.colorStatusInfoIcon, .color(colorStatusInfoIcon)),
            (.colorStatusSuccessBackground, .color(colorStatusSuccessBackground)),
            (.colorStatusSuccessForeground, .color(colorStatusSuccessForeground)),
            (.colorStatusSuccessBorder, .color(colorStatusSuccessBorder)),
            (.colorStatusSuccessIcon, .color(colorStatusSuccessIcon)),
            (.colorStatusWarningBackground, .color(colorStatusWarningBackground)),
            (.colorStatusWarningForeground, .color(colorStatusWarningForeground)),
            (.colorStatusWarningBorder, .color(colorStatusWarningBorder)),
            (.colorStatusWarningIcon, .color(colorStatusWarningIcon)),
            (.colorStatusDangerBackground, .color(colorStatusDangerBackground)),
            (.colorStatusDangerForeground, .color(colorStatusDangerForeground)),
        ]

        private static let entries3: [(TokenRef, TokenValue)] = [
            (.colorStatusDangerBorder, .color(colorStatusDangerBorder)),
            (.colorStatusDangerIcon, .color(colorStatusDangerIcon)),
            (.colorOverlayScrim, .color(colorOverlayScrim)),
            (.colorOverlaySurface, .color(colorOverlaySurface)),
            (.colorInverseSurface, .color(colorInverseSurface)),
            (.colorInverseForeground, .color(colorInverseForeground)),
            (.colorInverseMuted, .color(colorInverseMuted)),
            (.colorInverseLink, .color(colorInverseLink)),
            (.colorInverseFocus, .color(colorInverseFocus)),
            (.colorInverseStatusNeutral, .color(colorInverseStatusNeutral)),
            (.colorInverseStatusInfo, .color(colorInverseStatusInfo)),
            (.colorInverseStatusSuccess, .color(colorInverseStatusSuccess)),
            (.colorInverseStatusWarning, .color(colorInverseStatusWarning)),
            (.colorInverseStatusDanger, .color(colorInverseStatusDanger)),
            (.colorActionPrimaryBackground, .color(colorActionPrimaryBackground)),
            (.colorActionPrimaryBackgroundHover, .color(colorActionPrimaryBackgroundHover)),
            (.colorActionPrimaryForeground, .color(colorActionPrimaryForeground)),
            (.colorActionSecondaryBackground, .color(colorActionSecondaryBackground)),
            (.colorActionSecondaryBackgroundHover, .color(colorActionSecondaryBackgroundHover)),
            (.colorActionSecondaryForeground, .color(colorActionSecondaryForeground)),
            (.colorActionGhostBackground, .color(colorActionGhostBackground)),
            (.colorActionGhostBackgroundHover, .color(colorActionGhostBackgroundHover)),
            (.colorActionGhostForeground, .color(colorActionGhostForeground)),
            (.colorActionDangerBackground, .color(colorActionDangerBackground)),
            (.colorActionDangerBackgroundHover, .color(colorActionDangerBackgroundHover)),
            (.colorActionDangerForeground, .color(colorActionDangerForeground)),
            (.fontFamilyBody, .fontFamily(fontFamilyBody)),
            (.fontFamilyHeading, .fontFamily(fontFamilyHeading)),
            (.fontFamilyMono, .fontFamily(fontFamilyMono)),
            (.fontWeightRegular, .fontWeight(fontWeightRegular)),
            (.fontWeightMedium, .fontWeight(fontWeightMedium)),
            (.fontWeightSemibold, .fontWeight(fontWeightSemibold)),
        ]

        private static let entries4: [(TokenRef, TokenValue)] = [
            (.fontWeightBold, .fontWeight(fontWeightBold)),
            (.fontSizeXs, .dimension(fontSizeXs)),
            (.fontSizeSm, .dimension(fontSizeSm)),
            (.fontSizeMd, .dimension(fontSizeMd)),
            (.fontSizeLg, .dimension(fontSizeLg)),
            (.fontSizeXl, .dimension(fontSizeXl)),
            (.fontSize2xl, .dimension(fontSize2xl)),
            (.fontSize3xl, .dimension(fontSize3xl)),
            (.fontSize4xl, .dimension(fontSize4xl)),
            (.fontLineHeightTight, .number(fontLineHeightTight)),
            (.fontLineHeightNormal, .number(fontLineHeightNormal)),
            (.fontLineHeightLoose, .number(fontLineHeightLoose)),
            (.space0, .dimension(space0)),
            (.space1, .dimension(space1)),
            (.space2, .dimension(space2)),
            (.space3, .dimension(space3)),
            (.space4, .dimension(space4)),
            (.space5, .dimension(space5)),
            (.space6, .dimension(space6)),
            (.space8, .dimension(space8)),
            (.space10, .dimension(space10)),
            (.space12, .dimension(space12)),
            (.space16, .dimension(space16)),
            (.space20, .dimension(space20)),
            (.spaceSm, .dimension(spaceSm)),
            (.spaceMd, .dimension(spaceMd)),
            (.spaceLg, .dimension(spaceLg)),
            (.layoutGutterNarrow, .dimension(layoutGutterNarrow)),
            (.layoutGutter, .dimension(layoutGutter)),
            (.layoutGutterWide, .dimension(layoutGutterWide)),
            (.layoutSectionSm, .dimension(layoutSectionSm)),
            (.layoutSectionMd, .dimension(layoutSectionMd)),
        ]

        private static let entries5: [(TokenRef, TokenValue)] = [
            (.layoutSectionLg, .dimension(layoutSectionLg)),
            (.layoutGapNone, .dimension(layoutGapNone)),
            (.layoutGapTight, .dimension(layoutGapTight)),
            (.layoutGapNormal, .dimension(layoutGapNormal)),
            (.layoutGapLoose, .dimension(layoutGapLoose)),
            (.layoutGapSection, .dimension(layoutGapSection)),
            (.layoutInsetNone, .dimension(layoutInsetNone)),
            (.layoutInsetSm, .dimension(layoutInsetSm)),
            (.layoutInsetMd, .dimension(layoutInsetMd)),
            (.layoutInsetLg, .dimension(layoutInsetLg)),
            (.layoutInsetXl, .dimension(layoutInsetXl)),
            (.layoutMaxWidthProse, .dimension(layoutMaxWidthProse)),
            (.layoutMaxWidthContent, .dimension(layoutMaxWidthContent)),
            (.layoutMaxWidthPage, .dimension(layoutMaxWidthPage)),
            (.layoutBreakpointSm, .dimension(layoutBreakpointSm)),
            (.layoutBreakpointMd, .dimension(layoutBreakpointMd)),
            (.layoutBreakpointLg, .dimension(layoutBreakpointLg)),
            (.sizeTargetMin, .dimension(sizeTargetMin)),
            (.sizeTargetComfortable, .dimension(sizeTargetComfortable)),
            (.radiusNone, .dimension(radiusNone)),
            (.radiusSm, .dimension(radiusSm)),
            (.radiusMd, .dimension(radiusMd)),
            (.radiusLg, .dimension(radiusLg)),
            (.radiusFull, .dimension(radiusFull)),
            (.borderWidthThin, .dimension(borderWidthThin)),
            (.borderWidthFocus, .dimension(borderWidthFocus)),
            (.opacityDisabled, .number(opacityDisabled)),
            (.layerBase, .number(layerBase)),
            (.layerRaised, .number(layerRaised)),
            (.layerDropdown, .number(layerDropdown)),
            (.layerSheet, .number(layerSheet)),
            (.layerDialog, .number(layerDialog)),
        ]

        private static let entries6: [(TokenRef, TokenValue)] = [
            (.layerToast, .number(layerToast)),
            (.motionDurationFast, .duration(motionDurationFast)),
            (.motionDurationBase, .duration(motionDurationBase)),
            (.motionDurationLoop, .duration(motionDurationLoop)),
            (.motionEasingStandard, .animation(motionEasingStandard)),
            (.motionEasingExit, .animation(motionEasingExit)),
            (.shadowRaised, .shadow(shadowRaised)),
            (.shadowOverlay, .shadow(shadowOverlay)),
        ]

        public static let table = TokenTable(Dictionary(uniqueKeysWithValues: [entries0, entries1, entries2, entries3, entries4, entries5, entries6].joined()))
    }
}
