//  Themes.swift
//
//  Generated by tokens/build.mjs — do not edit; edit the theme docs and run `pnpm themes`.

/// The themes the token build emitted, in the order the docs list them.
public enum Themes {
    public static let all: [ThemeDefinition] = [
        CalmPrecise.definition,
        WarmFriendly.definition,
        WarmSleek.definition,
    ]

    /// What `\.dsTheme` resolves to when no `.dsTheme(_:)` is installed above a view.
    public static let fallback: ThemeDefinition = CalmPrecise.definition
}
