//  TokenRef.swift
//
//  Generated by tokens/build.mjs — do not edit; edit the theme docs and run `pnpm themes`.

import SwiftUI

/// Every token name the themes provide, as its dotted public name. This is the type an `overrides`
/// map is keyed by, and the type `theme[ref]` resolves.
public enum TokenRef: String, CaseIterable, Sendable {
    case colorPaletteNeutral0 = "color.palette.neutral.0"
    case colorPaletteNeutral50 = "color.palette.neutral.50"
    case colorPaletteNeutral100 = "color.palette.neutral.100"
    case colorPaletteNeutral200 = "color.palette.neutral.200"
    case colorPaletteNeutral300 = "color.palette.neutral.300"
    case colorPaletteNeutral400 = "color.palette.neutral.400"
    case colorPaletteNeutral500 = "color.palette.neutral.500"
    case colorPaletteNeutral600 = "color.palette.neutral.600"
    case colorPaletteNeutral700 = "color.palette.neutral.700"
    case colorPaletteNeutral800 = "color.palette.neutral.800"
    case colorPaletteNeutral900 = "color.palette.neutral.900"
    case colorPaletteNeutral1000 = "color.palette.neutral.1000"
    case colorPaletteBrand50 = "color.palette.brand.50"
    case colorPaletteBrand100 = "color.palette.brand.100"
    case colorPaletteBrand200 = "color.palette.brand.200"
    case colorPaletteBrand300 = "color.palette.brand.300"
    case colorPaletteBrand400 = "color.palette.brand.400"
    case colorPaletteBrand500 = "color.palette.brand.500"
    case colorPaletteBrand600 = "color.palette.brand.600"
    case colorPaletteBrand700 = "color.palette.brand.700"
    case colorPaletteBrand800 = "color.palette.brand.800"
    case colorPaletteBrand900 = "color.palette.brand.900"
    case colorPaletteDanger50 = "color.palette.danger.50"
    case colorPaletteDanger100 = "color.palette.danger.100"
    case colorPaletteDanger200 = "color.palette.danger.200"
    case colorPaletteDanger300 = "color.palette.danger.300"
    case colorPaletteDanger400 = "color.palette.danger.400"
    case colorPaletteDanger500 = "color.palette.danger.500"
    case colorPaletteDanger600 = "color.palette.danger.600"
    case colorPaletteDanger700 = "color.palette.danger.700"
    case colorPaletteDanger800 = "color.palette.danger.800"
    case colorPaletteDanger900 = "color.palette.danger.900"
    case colorPaletteSuccess50 = "color.palette.success.50"
    case colorPaletteSuccess100 = "color.palette.success.100"
    case colorPaletteSuccess200 = "color.palette.success.200"
    case colorPaletteSuccess300 = "color.palette.success.300"
    case colorPaletteSuccess400 = "color.palette.success.400"
    case colorPaletteSuccess500 = "color.palette.success.500"
    case colorPaletteSuccess600 = "color.palette.success.600"
    case colorPaletteSuccess700 = "color.palette.success.700"
    case colorPaletteSuccess800 = "color.palette.success.800"
    case colorPaletteSuccess900 = "color.palette.success.900"
    case colorPaletteWarning50 = "color.palette.warning.50"
    case colorPaletteWarning100 = "color.palette.warning.100"
    case colorPaletteWarning200 = "color.palette.warning.200"
    case colorPaletteWarning300 = "color.palette.warning.300"
    case colorPaletteWarning400 = "color.palette.warning.400"
    case colorPaletteWarning500 = "color.palette.warning.500"
    case colorPaletteWarning600 = "color.palette.warning.600"
    case colorPaletteWarning700 = "color.palette.warning.700"
    case colorPaletteWarning800 = "color.palette.warning.800"
    case colorPaletteWarning900 = "color.palette.warning.900"
    case colorPaletteInfo50 = "color.palette.info.50"
    case colorPaletteInfo100 = "color.palette.info.100"
    case colorPaletteInfo200 = "color.palette.info.200"
    case colorPaletteInfo300 = "color.palette.info.300"
    case colorPaletteInfo400 = "color.palette.info.400"
    case colorPaletteInfo500 = "color.palette.info.500"
    case colorPaletteInfo600 = "color.palette.info.600"
    case colorPaletteInfo700 = "color.palette.info.700"
    case colorPaletteInfo800 = "color.palette.info.800"
    case colorPaletteInfo900 = "color.palette.info.900"
    case colorForeground = "color.foreground"
    case colorForegroundStrong = "color.foreground.strong"
    case colorForegroundMuted = "color.foreground.muted"
    case colorForegroundOnAction = "color.foreground.onAction"
    case colorForegroundDanger = "color.foreground.danger"
    case colorBackground = "color.background"
    case colorBackgroundSubtle = "color.background.subtle"
    case colorBackgroundStrong = "color.background.strong"
    case colorBorder = "color.border"
    case colorBorderStrong = "color.border.strong"
    case colorBorderFocus = "color.border.focus"
    case colorBorderDanger = "color.border.danger"
    case colorLink = "color.link"
    case colorLinkHover = "color.link.hover"
    case colorLinkVisited = "color.link.visited"
    case colorControlBackground = "color.control.background"
    case colorControlBorder = "color.control.border"
    case colorControlSelectedBackground = "color.control.selectedBackground"
    case colorControlSelectedForeground = "color.control.selectedForeground"
    case colorControlTrackOff = "color.control.trackOff"
    case colorStatusInfoBackground = "color.status.info.background"
    case colorStatusInfoForeground = "color.status.info.foreground"
    case colorStatusInfoBorder = "color.status.info.border"
    case colorStatusInfoIcon = "color.status.info.icon"
    case colorStatusSuccessBackground = "color.status.success.background"
    case colorStatusSuccessForeground = "color.status.success.foreground"
    case colorStatusSuccessBorder = "color.status.success.border"
    case colorStatusSuccessIcon = "color.status.success.icon"
    case colorStatusWarningBackground = "color.status.warning.background"
    case colorStatusWarningForeground = "color.status.warning.foreground"
    case colorStatusWarningBorder = "color.status.warning.border"
    case colorStatusWarningIcon = "color.status.warning.icon"
    case colorStatusDangerBackground = "color.status.danger.background"
    case colorStatusDangerForeground = "color.status.danger.foreground"
    case colorStatusDangerBorder = "color.status.danger.border"
    case colorStatusDangerIcon = "color.status.danger.icon"
    case colorOverlayScrim = "color.overlay.scrim"
    case colorOverlaySurface = "color.overlay.surface"
    case colorInverseSurface = "color.inverse.surface"
    case colorInverseForeground = "color.inverse.foreground"
    case colorInverseMuted = "color.inverse.muted"
    case colorInverseLink = "color.inverse.link"
    case colorInverseFocus = "color.inverse.focus"
    case colorInverseStatusNeutral = "color.inverse.status.neutral"
    case colorInverseStatusInfo = "color.inverse.status.info"
    case colorInverseStatusSuccess = "color.inverse.status.success"
    case colorInverseStatusWarning = "color.inverse.status.warning"
    case colorInverseStatusDanger = "color.inverse.status.danger"
    case colorActionPrimaryBackground = "color.action.primary.background"
    case colorActionPrimaryBackgroundHover = "color.action.primary.backgroundHover"
    case colorActionPrimaryForeground = "color.action.primary.foreground"
    case colorActionSecondaryBackground = "color.action.secondary.background"
    case colorActionSecondaryBackgroundHover = "color.action.secondary.backgroundHover"
    case colorActionSecondaryForeground = "color.action.secondary.foreground"
    case colorActionGhostBackground = "color.action.ghost.background"
    case colorActionGhostBackgroundHover = "color.action.ghost.backgroundHover"
    case colorActionGhostForeground = "color.action.ghost.foreground"
    case colorActionDangerBackground = "color.action.danger.background"
    case colorActionDangerBackgroundHover = "color.action.danger.backgroundHover"
    case colorActionDangerForeground = "color.action.danger.foreground"
    case fontFamilyBody = "font.family.body"
    case fontFamilyHeading = "font.family.heading"
    case fontFamilyMono = "font.family.mono"
    case fontWeightRegular = "font.weight.regular"
    case fontWeightMedium = "font.weight.medium"
    case fontWeightSemibold = "font.weight.semibold"
    case fontWeightBold = "font.weight.bold"
    case fontSizeXs = "font.size.xs"
    case fontSizeSm = "font.size.sm"
    case fontSizeMd = "font.size.md"
    case fontSizeLg = "font.size.lg"
    case fontSizeXl = "font.size.xl"
    case fontSize2xl = "font.size.2xl"
    case fontSize3xl = "font.size.3xl"
    case fontSize4xl = "font.size.4xl"
    case fontLineHeightTight = "font.lineHeight.tight"
    case fontLineHeightNormal = "font.lineHeight.normal"
    case fontLineHeightLoose = "font.lineHeight.loose"
    case space0 = "space.0"
    case space1 = "space.1"
    case space2 = "space.2"
    case space3 = "space.3"
    case space4 = "space.4"
    case space5 = "space.5"
    case space6 = "space.6"
    case space8 = "space.8"
    case space10 = "space.10"
    case space12 = "space.12"
    case space16 = "space.16"
    case space20 = "space.20"
    case spaceSm = "space.sm"
    case spaceMd = "space.md"
    case spaceLg = "space.lg"
    case layoutGutterNarrow = "layout.gutter.narrow"
    case layoutGutter = "layout.gutter"
    case layoutGutterWide = "layout.gutter.wide"
    case layoutSectionSm = "layout.section.sm"
    case layoutSectionMd = "layout.section.md"
    case layoutSectionLg = "layout.section.lg"
    case layoutGapNone = "layout.gap.none"
    case layoutGapTight = "layout.gap.tight"
    case layoutGapNormal = "layout.gap.normal"
    case layoutGapLoose = "layout.gap.loose"
    case layoutGapSection = "layout.gap.section"
    case layoutInsetNone = "layout.inset.none"
    case layoutInsetSm = "layout.inset.sm"
    case layoutInsetMd = "layout.inset.md"
    case layoutInsetLg = "layout.inset.lg"
    case layoutInsetXl = "layout.inset.xl"
    case layoutMaxWidthProse = "layout.maxWidth.prose"
    case layoutMaxWidthContent = "layout.maxWidth.content"
    case layoutMaxWidthPage = "layout.maxWidth.page"
    case layoutBreakpointSm = "layout.breakpoint.sm"
    case layoutBreakpointMd = "layout.breakpoint.md"
    case layoutBreakpointLg = "layout.breakpoint.lg"
    case sizeTargetMin = "size.target.min"
    case sizeTargetComfortable = "size.target.comfortable"
    case radiusNone = "radius.none"
    case radiusSm = "radius.sm"
    case radiusMd = "radius.md"
    case radiusLg = "radius.lg"
    case radiusFull = "radius.full"
    case borderWidthThin = "border.width.thin"
    case borderWidthFocus = "border.width.focus"
    case opacityDisabled = "opacity.disabled"
    case layerBase = "layer.base"
    case layerRaised = "layer.raised"
    case layerDropdown = "layer.dropdown"
    case layerSheet = "layer.sheet"
    case layerDialog = "layer.dialog"
    case layerToast = "layer.toast"
    case motionDurationFast = "motion.duration.fast"
    case motionDurationBase = "motion.duration.base"
    case motionDurationLoop = "motion.duration.loop"
    case motionEasingStandard = "motion.easing.standard"
    case motionEasingExit = "motion.easing.exit"
    case shadowRaised = "shadow.raised"
    case shadowOverlay = "shadow.overlay"
}

/// The named accessors, resolved for whichever mode the theme was built with — a component reads
/// `theme.colorBackground` and never asks which color scheme it is in.
public extension Theme {
    var colorPaletteNeutral0: Color { color(.colorPaletteNeutral0) }
    var colorPaletteNeutral50: Color { color(.colorPaletteNeutral50) }
    var colorPaletteNeutral100: Color { color(.colorPaletteNeutral100) }
    var colorPaletteNeutral200: Color { color(.colorPaletteNeutral200) }
    var colorPaletteNeutral300: Color { color(.colorPaletteNeutral300) }
    var colorPaletteNeutral400: Color { color(.colorPaletteNeutral400) }
    var colorPaletteNeutral500: Color { color(.colorPaletteNeutral500) }
    var colorPaletteNeutral600: Color { color(.colorPaletteNeutral600) }
    var colorPaletteNeutral700: Color { color(.colorPaletteNeutral700) }
    var colorPaletteNeutral800: Color { color(.colorPaletteNeutral800) }
    var colorPaletteNeutral900: Color { color(.colorPaletteNeutral900) }
    var colorPaletteNeutral1000: Color { color(.colorPaletteNeutral1000) }
    var colorPaletteBrand50: Color { color(.colorPaletteBrand50) }
    var colorPaletteBrand100: Color { color(.colorPaletteBrand100) }
    var colorPaletteBrand200: Color { color(.colorPaletteBrand200) }
    var colorPaletteBrand300: Color { color(.colorPaletteBrand300) }
    var colorPaletteBrand400: Color { color(.colorPaletteBrand400) }
    var colorPaletteBrand500: Color { color(.colorPaletteBrand500) }
    var colorPaletteBrand600: Color { color(.colorPaletteBrand600) }
    var colorPaletteBrand700: Color { color(.colorPaletteBrand700) }
    var colorPaletteBrand800: Color { color(.colorPaletteBrand800) }
    var colorPaletteBrand900: Color { color(.colorPaletteBrand900) }
    var colorPaletteDanger50: Color { color(.colorPaletteDanger50) }
    var colorPaletteDanger100: Color { color(.colorPaletteDanger100) }
    var colorPaletteDanger200: Color { color(.colorPaletteDanger200) }
    var colorPaletteDanger300: Color { color(.colorPaletteDanger300) }
    var colorPaletteDanger400: Color { color(.colorPaletteDanger400) }
    var colorPaletteDanger500: Color { color(.colorPaletteDanger500) }
    var colorPaletteDanger600: Color { color(.colorPaletteDanger600) }
    var colorPaletteDanger700: Color { color(.colorPaletteDanger700) }
    var colorPaletteDanger800: Color { color(.colorPaletteDanger800) }
    var colorPaletteDanger900: Color { color(.colorPaletteDanger900) }
    var colorPaletteSuccess50: Color { color(.colorPaletteSuccess50) }
    var colorPaletteSuccess100: Color { color(.colorPaletteSuccess100) }
    var colorPaletteSuccess200: Color { color(.colorPaletteSuccess200) }
    var colorPaletteSuccess300: Color { color(.colorPaletteSuccess300) }
    var colorPaletteSuccess400: Color { color(.colorPaletteSuccess400) }
    var colorPaletteSuccess500: Color { color(.colorPaletteSuccess500) }
    var colorPaletteSuccess600: Color { color(.colorPaletteSuccess600) }
    var colorPaletteSuccess700: Color { color(.colorPaletteSuccess700) }
    var colorPaletteSuccess800: Color { color(.colorPaletteSuccess800) }
    var colorPaletteSuccess900: Color { color(.colorPaletteSuccess900) }
    var colorPaletteWarning50: Color { color(.colorPaletteWarning50) }
    var colorPaletteWarning100: Color { color(.colorPaletteWarning100) }
    var colorPaletteWarning200: Color { color(.colorPaletteWarning200) }
    var colorPaletteWarning300: Color { color(.colorPaletteWarning300) }
    var colorPaletteWarning400: Color { color(.colorPaletteWarning400) }
    var colorPaletteWarning500: Color { color(.colorPaletteWarning500) }
    var colorPaletteWarning600: Color { color(.colorPaletteWarning600) }
    var colorPaletteWarning700: Color { color(.colorPaletteWarning700) }
    var colorPaletteWarning800: Color { color(.colorPaletteWarning800) }
    var colorPaletteWarning900: Color { color(.colorPaletteWarning900) }
    var colorPaletteInfo50: Color { color(.colorPaletteInfo50) }
    var colorPaletteInfo100: Color { color(.colorPaletteInfo100) }
    var colorPaletteInfo200: Color { color(.colorPaletteInfo200) }
    var colorPaletteInfo300: Color { color(.colorPaletteInfo300) }
    var colorPaletteInfo400: Color { color(.colorPaletteInfo400) }
    var colorPaletteInfo500: Color { color(.colorPaletteInfo500) }
    var colorPaletteInfo600: Color { color(.colorPaletteInfo600) }
    var colorPaletteInfo700: Color { color(.colorPaletteInfo700) }
    var colorPaletteInfo800: Color { color(.colorPaletteInfo800) }
    var colorPaletteInfo900: Color { color(.colorPaletteInfo900) }
    var colorForeground: Color { color(.colorForeground) }
    var colorForegroundStrong: Color { color(.colorForegroundStrong) }
    var colorForegroundMuted: Color { color(.colorForegroundMuted) }
    var colorForegroundOnAction: Color { color(.colorForegroundOnAction) }
    var colorForegroundDanger: Color { color(.colorForegroundDanger) }
    var colorBackground: Color { color(.colorBackground) }
    var colorBackgroundSubtle: Color { color(.colorBackgroundSubtle) }
    var colorBackgroundStrong: Color { color(.colorBackgroundStrong) }
    var colorBorder: Color { color(.colorBorder) }
    var colorBorderStrong: Color { color(.colorBorderStrong) }
    var colorBorderFocus: Color { color(.colorBorderFocus) }
    var colorBorderDanger: Color { color(.colorBorderDanger) }
    var colorLink: Color { color(.colorLink) }
    var colorLinkHover: Color { color(.colorLinkHover) }
    var colorLinkVisited: Color { color(.colorLinkVisited) }
    var colorControlBackground: Color { color(.colorControlBackground) }
    var colorControlBorder: Color { color(.colorControlBorder) }
    var colorControlSelectedBackground: Color { color(.colorControlSelectedBackground) }
    var colorControlSelectedForeground: Color { color(.colorControlSelectedForeground) }
    var colorControlTrackOff: Color { color(.colorControlTrackOff) }
    var colorStatusInfoBackground: Color { color(.colorStatusInfoBackground) }
    var colorStatusInfoForeground: Color { color(.colorStatusInfoForeground) }
    var colorStatusInfoBorder: Color { color(.colorStatusInfoBorder) }
    var colorStatusInfoIcon: Color { color(.colorStatusInfoIcon) }
    var colorStatusSuccessBackground: Color { color(.colorStatusSuccessBackground) }
    var colorStatusSuccessForeground: Color { color(.colorStatusSuccessForeground) }
    var colorStatusSuccessBorder: Color { color(.colorStatusSuccessBorder) }
    var colorStatusSuccessIcon: Color { color(.colorStatusSuccessIcon) }
    var colorStatusWarningBackground: Color { color(.colorStatusWarningBackground) }
    var colorStatusWarningForeground: Color { color(.colorStatusWarningForeground) }
    var colorStatusWarningBorder: Color { color(.colorStatusWarningBorder) }
    var colorStatusWarningIcon: Color { color(.colorStatusWarningIcon) }
    var colorStatusDangerBackground: Color { color(.colorStatusDangerBackground) }
    var colorStatusDangerForeground: Color { color(.colorStatusDangerForeground) }
    var colorStatusDangerBorder: Color { color(.colorStatusDangerBorder) }
    var colorStatusDangerIcon: Color { color(.colorStatusDangerIcon) }
    var colorOverlayScrim: Color { color(.colorOverlayScrim) }
    var colorOverlaySurface: Color { color(.colorOverlaySurface) }
    var colorInverseSurface: Color { color(.colorInverseSurface) }
    var colorInverseForeground: Color { color(.colorInverseForeground) }
    var colorInverseMuted: Color { color(.colorInverseMuted) }
    var colorInverseLink: Color { color(.colorInverseLink) }
    var colorInverseFocus: Color { color(.colorInverseFocus) }
    var colorInverseStatusNeutral: Color { color(.colorInverseStatusNeutral) }
    var colorInverseStatusInfo: Color { color(.colorInverseStatusInfo) }
    var colorInverseStatusSuccess: Color { color(.colorInverseStatusSuccess) }
    var colorInverseStatusWarning: Color { color(.colorInverseStatusWarning) }
    var colorInverseStatusDanger: Color { color(.colorInverseStatusDanger) }
    var colorActionPrimaryBackground: Color { color(.colorActionPrimaryBackground) }
    var colorActionPrimaryBackgroundHover: Color { color(.colorActionPrimaryBackgroundHover) }
    var colorActionPrimaryForeground: Color { color(.colorActionPrimaryForeground) }
    var colorActionSecondaryBackground: Color { color(.colorActionSecondaryBackground) }
    var colorActionSecondaryBackgroundHover: Color { color(.colorActionSecondaryBackgroundHover) }
    var colorActionSecondaryForeground: Color { color(.colorActionSecondaryForeground) }
    var colorActionGhostBackground: Color { color(.colorActionGhostBackground) }
    var colorActionGhostBackgroundHover: Color { color(.colorActionGhostBackgroundHover) }
    var colorActionGhostForeground: Color { color(.colorActionGhostForeground) }
    var colorActionDangerBackground: Color { color(.colorActionDangerBackground) }
    var colorActionDangerBackgroundHover: Color { color(.colorActionDangerBackgroundHover) }
    var colorActionDangerForeground: Color { color(.colorActionDangerForeground) }
    var fontFamilyBody: FontFamilyToken { fontFamily(.fontFamilyBody) }
    var fontFamilyHeading: FontFamilyToken { fontFamily(.fontFamilyHeading) }
    var fontFamilyMono: FontFamilyToken { fontFamily(.fontFamilyMono) }
    var fontWeightRegular: Font.Weight { fontWeight(.fontWeightRegular) }
    var fontWeightMedium: Font.Weight { fontWeight(.fontWeightMedium) }
    var fontWeightSemibold: Font.Weight { fontWeight(.fontWeightSemibold) }
    var fontWeightBold: Font.Weight { fontWeight(.fontWeightBold) }
    var fontSizeXs: CGFloat { dimension(.fontSizeXs) }
    var fontSizeSm: CGFloat { dimension(.fontSizeSm) }
    var fontSizeMd: CGFloat { dimension(.fontSizeMd) }
    var fontSizeLg: CGFloat { dimension(.fontSizeLg) }
    var fontSizeXl: CGFloat { dimension(.fontSizeXl) }
    var fontSize2xl: CGFloat { dimension(.fontSize2xl) }
    var fontSize3xl: CGFloat { dimension(.fontSize3xl) }
    var fontSize4xl: CGFloat { dimension(.fontSize4xl) }
    var fontLineHeightTight: Double { number(.fontLineHeightTight) }
    var fontLineHeightNormal: Double { number(.fontLineHeightNormal) }
    var fontLineHeightLoose: Double { number(.fontLineHeightLoose) }
    var space0: CGFloat { dimension(.space0) }
    var space1: CGFloat { dimension(.space1) }
    var space2: CGFloat { dimension(.space2) }
    var space3: CGFloat { dimension(.space3) }
    var space4: CGFloat { dimension(.space4) }
    var space5: CGFloat { dimension(.space5) }
    var space6: CGFloat { dimension(.space6) }
    var space8: CGFloat { dimension(.space8) }
    var space10: CGFloat { dimension(.space10) }
    var space12: CGFloat { dimension(.space12) }
    var space16: CGFloat { dimension(.space16) }
    var space20: CGFloat { dimension(.space20) }
    var spaceSm: CGFloat { dimension(.spaceSm) }
    var spaceMd: CGFloat { dimension(.spaceMd) }
    var spaceLg: CGFloat { dimension(.spaceLg) }
    var layoutGutterNarrow: CGFloat { dimension(.layoutGutterNarrow) }
    var layoutGutter: CGFloat { dimension(.layoutGutter) }
    var layoutGutterWide: CGFloat { dimension(.layoutGutterWide) }
    var layoutSectionSm: CGFloat { dimension(.layoutSectionSm) }
    var layoutSectionMd: CGFloat { dimension(.layoutSectionMd) }
    var layoutSectionLg: CGFloat { dimension(.layoutSectionLg) }
    var layoutGapNone: CGFloat { dimension(.layoutGapNone) }
    var layoutGapTight: CGFloat { dimension(.layoutGapTight) }
    var layoutGapNormal: CGFloat { dimension(.layoutGapNormal) }
    var layoutGapLoose: CGFloat { dimension(.layoutGapLoose) }
    var layoutGapSection: CGFloat { dimension(.layoutGapSection) }
    var layoutInsetNone: CGFloat { dimension(.layoutInsetNone) }
    var layoutInsetSm: CGFloat { dimension(.layoutInsetSm) }
    var layoutInsetMd: CGFloat { dimension(.layoutInsetMd) }
    var layoutInsetLg: CGFloat { dimension(.layoutInsetLg) }
    var layoutInsetXl: CGFloat { dimension(.layoutInsetXl) }
    var layoutMaxWidthProse: CGFloat { dimension(.layoutMaxWidthProse) }
    var layoutMaxWidthContent: CGFloat { dimension(.layoutMaxWidthContent) }
    var layoutMaxWidthPage: CGFloat { dimension(.layoutMaxWidthPage) }
    var layoutBreakpointSm: CGFloat { dimension(.layoutBreakpointSm) }
    var layoutBreakpointMd: CGFloat { dimension(.layoutBreakpointMd) }
    var layoutBreakpointLg: CGFloat { dimension(.layoutBreakpointLg) }
    var sizeTargetMin: CGFloat { dimension(.sizeTargetMin) }
    var sizeTargetComfortable: CGFloat { dimension(.sizeTargetComfortable) }
    var radiusNone: CGFloat { dimension(.radiusNone) }
    var radiusSm: CGFloat { dimension(.radiusSm) }
    var radiusMd: CGFloat { dimension(.radiusMd) }
    var radiusLg: CGFloat { dimension(.radiusLg) }
    var radiusFull: CGFloat { dimension(.radiusFull) }
    var borderWidthThin: CGFloat { dimension(.borderWidthThin) }
    var borderWidthFocus: CGFloat { dimension(.borderWidthFocus) }
    var opacityDisabled: Double { number(.opacityDisabled) }
    var layerBase: Double { number(.layerBase) }
    var layerRaised: Double { number(.layerRaised) }
    var layerDropdown: Double { number(.layerDropdown) }
    var layerSheet: Double { number(.layerSheet) }
    var layerDialog: Double { number(.layerDialog) }
    var layerToast: Double { number(.layerToast) }
    var motionDurationFast: TimeInterval { duration(.motionDurationFast) }
    var motionDurationBase: TimeInterval { duration(.motionDurationBase) }
    var motionDurationLoop: TimeInterval { duration(.motionDurationLoop) }
    var motionEasingStandard: Animation { animation(.motionEasingStandard) }
    var motionEasingExit: Animation { animation(.motionEasingExit) }
    var shadowRaised: ShadowToken { shadow(.shadowRaised) }
    var shadowOverlay: ShadowToken { shadow(.shadowOverlay) }
}
