// Generated by tools/naming.ts from themes/demo-brand/naming.md (aliases). Do not edit; --revert deletes this folder.
import { createElement, type ComponentProps, type ReactElement } from 'react';
import { CtaButton as CtaButtonBase } from '../CtaButton';

/* Only declared when the bundler defines it; never assumed. */
declare const process: { env: Record<string, string | undefined> } | undefined;
const isDev = typeof process !== 'undefined' && process.env.NODE_ENV !== 'production';

type CtaButtonBaseProps = ComponentProps<typeof CtaButtonBase>;
type EmphasisValue = NonNullable<CtaButtonBaseProps['emphasis']>;

/**
 * CtaButton's props, with the old spellings themes/demo-brand/naming.md keeps working: `kind` and `cta`.
 * @deprecated since 2.0.0; pass the current names and import CtaButton's own props from the package.
 */
export type CtaButtonProps = Omit<CtaButtonBaseProps, 'emphasis'> & {
  /** Also takes the old value `cta`, deprecated. */
  emphasis?: EmphasisValue | 'cta' | undefined;
  /** @deprecated since 2.0.0; use `emphasis`. */
  kind?: EmphasisValue | 'cta' | undefined;
};

const warned = new Set<string>();

function warnOnce(key: string, message: string): void {
  if (!isDev || warned.has(key)) return;
  warned.add(key);
  console.warn(message);
}

/**
 * CtaButton, taking the old spellings `kind` and `cta` and passing the current ones on.
 * @deprecated since 2.0.0; import CtaButton from the package once callers use the current names.
 */
export function CtaButton({ emphasis: emphasisValue, kind: kindValue, ...rest }: CtaButtonProps): ReactElement {
  if (kindValue !== undefined) warnOnce('kind', 'CtaButton: `kind` is deprecated since 2.0.0; use `emphasis`.');
  const emphasisChosen = emphasisValue ?? kindValue;
  if (emphasisChosen === 'cta') warnOnce('emphasis=cta', 'CtaButton: `cta` is deprecated since 2.0.0; use `primary`.');
  const props: CtaButtonBaseProps = { ...rest };
  if (emphasisChosen !== undefined) props.emphasis = emphasisChosen === 'cta' ? 'primary' : emphasisChosen;
  return createElement(CtaButtonBase, props);
}

/** @deprecated since 2.0.0; use `CtaButton`. */
export const ActionButton: typeof CtaButton = CtaButton;
/** @deprecated since 2.0.0; use `CtaButton`'s props. */
export type ActionButtonProps = CtaButtonProps;
