// swift-tools-version: 6.2
//
// DesignSchema for iOS — process/ios-platform.md ("Package layout").
//
// Platforms: the deployment target is the current iOS major minus one, reviewed each September
// (process/ios-platform.md). iOS 27 ships 2026-09-14, so the floor is iOS 26 from that week; until then
// it is the current major and the rule is a no-op. `.macOS(.v26)` is declared as well — not because the
// package ships a Mac product, but because `swift build` on the CI runner builds for the host, and the
// SwiftUI APIs the components use (`.onKeyPress`, `AccessibilityNotification`, `@AccessibilityFocusState`)
// only typecheck against a macOS 14+ floor. The simulator/device build is `xcodebuild -destination
// 'generic/platform=iOS'` in .github/workflows/swiftui-gates.yml (job 440).
//
// Swift 6 language mode (the default at this tools version) — strict concurrency, per the plan.
// No third-party dependency may be added here: SwiftUI and Foundation only.

import PackageDescription

let package = Package(
    name: "DesignSchema",
    platforms: [
        .iOS(.v26),
        .macOS(.v26),
    ],
    products: [
        // The token layer on its own: Theme, TokenRef, the generated theme tables.
        .library(name: "DesignSchemaTokens", targets: ["DesignSchemaTokens"]),
        // The components.
        .library(name: "DesignSchema", targets: ["DesignSchema"]),
    ],
    targets: [
        // Generated by the token build (job 410) apart from Theme.swift, which is the contract the
        // generated files fill in.
        .target(name: "DesignSchemaTokens"),
        // One file per component, plus Support/ (FocusScope, Portal, Announce, ReducedMotion, Gallery).
        .target(name: "DesignSchema", dependencies: ["DesignSchemaTokens"]),
        // Swift Testing: the docs' `behavior` scenarios (job 460).
        .testTarget(name: "DesignSchemaTests", dependencies: ["DesignSchema"]),
        // XCUITest: performAccessibilityAudit per component and the keyboard spec on an iPad simulator
        // (job 440). SwiftPM cannot host a UI test run, so this target only *builds* here — it is an empty
        // module off iOS — and the bundle that runs is built from apps/ios-gallery/project.yml, which
        // compiles these same files against the gallery app.
        .testTarget(name: "DesignSchemaUITests", dependencies: ["DesignSchema"]),
    ]
)
