#!/usr/bin/env node
/**
 * Deterministic gate: every module an extension declares exists, exports its name, and matches its
 * declared signature.
 *
 * Extension docs (site/src/content/docs/extensions/*.md) may declare hand-written modules under
 * packages/<platform>/src/custom/. tools/parse.ts writes a .d.ts stub per module from the declared
 * signature into generated/modules/<platform>/; this gate checks, for one platform:
 *
 *   1. packages/<pkg>/src/<path> exists
 *   2. it exports the declared name (a plain-text scan for `export function|const|let|class <name>`
 *      or `export { ..., <name>, ... }`)
 *   3. the real export is assignable to the stub's type — a tiny generated TypeScript program,
 *      packages/<pkg>/.modules-check/check.ts (inside the package so its tsconfig, node_modules and
 *      ambient types resolve exactly as they do for the package), compiled with
 *      `pnpm --filter @design-schema/<pkg> exec tsc -p .modules-check/tsconfig.json`
 *
 * Nothing is checked when no extension declares a module for the platform. The gate reads
 * generated/components.json (each entry's `extensions[].modules`), so parse must have run.
 *
 * Usage:  node tools/check_modules.ts --platform web [--no-typecheck]
 * Exit 1 on any finding.
 *
 * Port of tools/check_modules.py: same flags, same findings, same lines on stdout, same exit codes.
 * Windows spawns `pnpm` (a `.cmd`) through cmd.exe pre-quoted, the way tools/checks.ts does — the
 * repository path has a space in it. Runs under Node's type stripping: annotations only.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { which, winQuote } from './lib/proc.ts';
import { pyJsonDumps, pyReEscape, pyStrip, readText, truthy, writeText } from './lib/py.ts';
import { REPO_ROOT } from './lib/root.ts';

/** Every path the tool reads or writes. The tests pass their own sandbox to `run`. */
export const paths = { ROOT: REPO_ROOT, GENERATED: join(REPO_ROOT, 'generated'), PACKAGES: join(REPO_ROOT, 'packages') };

export const PKG: Record<string, string> = { web: 'react', lit: 'lit', rn: 'rn' };
export const CHECK_DIR = '.modules-check'; // inside the package, git-ignored
// What the check program imports so the platform's globals (`__DEV__`) are declared in the program.
const PREAMBLE: Record<string, string[]> = { web: [], lit: [], rn: ["import 'react-native';"] };

export type Dict = Record<string, any>;
export type Module = { component: string; extension: string; name: string; path: string; signature: string };

/** Every module that targets the platform, in document order. */
export function declaredModules(components: Dict[], platform: string): Module[] {
  const out: Module[] = [];
  for (const e of components) {
    for (const ext of truthy(e.extensions) ? (e.extensions as Dict[]) : []) {
      for (const [name, m] of Object.entries(truthy(ext.modules) ? (ext.modules as Dict) : {})) {
        const mod = m as Dict;
        if (truthy(mod.platforms) && !(mod.platforms as string[]).includes(platform)) continue;
        out.push({ component: e.component.name as string, extension: ext.name as string, name, path: mod.path as string, signature: mod.signature as string });
      }
    }
  }
  return out;
}

export function exportsName(source: string, name: string): boolean {
  if (new RegExp(`^\\s*export\\s+(?:async\\s+)?(?:function\\*?|const|let|var|class)\\s+${pyReEscape(name)}\\b`, 'm').test(source)) return true;
  for (const m of source.matchAll(/^\s*export\s*\{([^}]*)\}/gm)) {
    const names = (m[1] as string).split(',').map((part) => pyStrip(pyStrip(part).split(' as ').pop() as string));
    if (names.includes(name)) return true;
  }
  return false;
}

/** Forward-slash relative path that always starts with ./ or ../ (a bare name would be a package import). */
export function relpath(target: string, start: string): string {
  const rel = relative(start, target).replaceAll('\\', '/');
  return rel.startsWith('.') ? rel : './' + rel;
}

/** `Path.with_suffix("")`: drop the last extension, if any. */
function stripSuffix(p: string): string {
  const ext = extname(p);
  return ext ? p.slice(0, -ext.length) : p;
}

/** The TypeScript that proves each real export is assignable to its stub. */
export function checkProgram(modules: Module[], platform: string, checkDir: string, stubsDir: string): string {
  const src = join(dirname(checkDir), 'src');
  const lines = ['// Generated by tools/check_modules.ts: assignability of each custom module to its declared stub. Do not edit.'];
  lines.push(...(PREAMBLE[platform] as string[]));
  modules.forEach((m, i) => {
    const real = relpath(stripSuffix(join(src, m.path)), checkDir);
    const stub = relpath(stripSuffix(join(stubsDir, m.path)), checkDir);
    lines.push(
      `import * as real${i} from '${real}';`,
      `import type * as stub${i} from '${stub}';`,
      `const check${i}: typeof stub${i}.${m.name} = real${i}.${m.name};`,
      `void check${i};`,
    );
  });
  return lines.join('\n') + '\n';
}

// rootDir widens to the repo root: check.ts imports the stubs under generated/modules/, outside the
// package's own rootDir.
export function tsconfig(): Dict {
  return {
    extends: '../tsconfig.json',
    compilerOptions: { noEmit: true, composite: false, incremental: false, rootDir: '../..' },
    include: ['check.ts'],
  };
}

export function pnpm(): string {
  return which('pnpm') ?? which('pnpm.cmd') ?? 'pnpm';
}

export type RunOptions = { typecheck?: boolean; components?: Dict[] | null; packages?: string; generated?: string };

export function run(platform: string, options: RunOptions = {}): string[] {
  const { typecheck = true, packages = paths.PACKAGES, generated = paths.GENERATED } = options;
  let components = options.components ?? null;
  if (components === null) {
    const cj = join(generated, 'components.json');
    if (!existsSync(cj)) return ['generated/components.json missing — run tools/parse.ts'];
    components = JSON.parse(readFileSync(cj, 'utf8')) as Dict[];
  }
  const modules = declaredModules(components, platform);
  if (!modules.length) return [];
  const findings: string[] = [];
  const pkg = PKG[platform] as string;
  const pkgDir = join(packages, pkg);
  const present: Module[] = [];
  for (const m of modules) {
    const f = join(pkgDir, 'src', m.path);
    const where = `${m.component}.${m.extension}`;
    if (!existsSync(f)) {
      findings.push(`${where}: module '${m.name}' expects packages/${pkg}/src/${m.path}, which does not exist`);
      continue;
    }
    if (!exportsName(readText(f), m.name)) {
      findings.push(`${where}: packages/${pkg}/src/${m.path} does not export '${m.name}'`);
      continue;
    }
    present.push(m);
  }
  if (findings.length || !typecheck || !present.length) return findings;
  const checkDir = join(pkgDir, CHECK_DIR);
  mkdirSync(checkDir, { recursive: true });
  writeText(join(checkDir, 'check.ts'), checkProgram(present, platform, checkDir, join(generated, 'modules', platform)));
  writeText(join(checkDir, 'tsconfig.json'), pyJsonDumps(tsconfig(), 2) + '\n');
  const argv = [pnpm(), '--filter', `@design-schema/${pkg}`, 'exec', 'tsc', '-p', `${CHECK_DIR}/tsconfig.json`];
  const spawnOptions = { cwd: paths.ROOT, encoding: 'utf8' as const, maxBuffer: 64 * 1024 * 1024 };
  const p =
    process.platform === 'win32'
      ? spawnSync(argv.map(winQuote).join(' '), { ...spawnOptions, shell: true })
      : spawnSync(argv[0] as string, argv.slice(1), spawnOptions);
  if (p.status !== 0) {
    const out = pyStrip(((p.stdout ?? '') + (p.stderr ?? '')).replace(/\r\n?/g, '\n'));
    findings.push(`a custom module does not match its declared signature (packages/${pkg}/${CHECK_DIR}/check.ts):\n${[...out].slice(-3000).join('')}`);
  }
  return findings;
}

export type Args = { platform: string; noTypecheck: boolean };

/** argparse's `--platform {web,lit,rn}` (required) and `--no-typecheck`. */
export function parseArgs(argv: string[], prog: string = 'check_modules.ts'): Args {
  const usage = `usage: ${prog} [-h] --platform {web,lit,rn} [--no-typecheck]`;
  const die: (message: string) => never = (message) => {
    process.stderr.write(`${usage}\n${prog}: error: ${message}\n`);
    throw Object.assign(new Error(message), { exitCode: 2 });
  };
  const args: Args = { platform: '', noTypecheck: false };
  const unrecognized: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] as string;
    if (arg === '-h' || arg === '--help') {
      process.stdout.write(`${usage}\n`);
      throw Object.assign(new Error('help'), { exitCode: 0 });
    } else if (arg === '--platform' || arg.startsWith('--platform=')) {
      const value = arg.startsWith('--platform=') ? arg.slice('--platform='.length) : argv[++i];
      if (value === undefined) die('argument --platform: expected one argument');
      if (!Object.hasOwn(PKG, value)) die(`argument --platform: invalid choice: '${value}' (choose from ${Object.keys(PKG).join(', ')})`);
      args.platform = value;
    } else if (arg === '--no-typecheck') {
      args.noTypecheck = true;
    } else {
      unrecognized.push(arg); // argparse collects these and reports them *after* the required-argument check
    }
  }
  if (!args.platform) die('the following arguments are required: --platform');
  if (unrecognized.length) die(`unrecognized arguments: ${unrecognized.join(' ')}`);
  return args;
}

export function main(argv: string[] = process.argv.slice(2)): number {
  let a: Args;
  try {
    a = parseArgs(argv);
  } catch (e) {
    return (e as { exitCode?: number }).exitCode ?? 2;
  }
  const findings = run(a.platform, { typecheck: !a.noTypecheck });
  for (const f of findings) process.stdout.write(`✖ ${f}\n`);
  const cj = join(paths.GENERATED, 'components.json');
  const n = existsSync(cj) ? declaredModules(JSON.parse(readFileSync(cj, 'utf8')) as Dict[], a.platform).length : 0;
  process.stdout.write(`${findings.length ? '✖' : '✔'} check_modules (${a.platform}): ${n} module(s), ${findings.length} finding(s)\n`);
  return findings.length ? 1 : 0;
}

const invokedDirectly = process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) process.exitCode = main();
