"""
Deterministic gate: every module an extension declares exists, exports its name, and matches its
declared signature.

Extension docs (site/src/content/docs/extensions/*.md) may declare hand-written modules under
packages/<platform>/src/custom/. tools/parse.py writes a .d.ts stub per module from the declared
signature into generated/modules/<platform>/; this gate checks, for one platform:

  1. packages/<pkg>/src/<path> exists
  2. it exports the declared name (a plain-text scan for `export function|const|let|class <name>`
     or `export { ..., <name>, ... }`)
  3. the real export is assignable to the stub's type — a tiny generated TypeScript program,
     packages/<pkg>/.modules-check/check.ts (inside the package so its tsconfig, node_modules and
     ambient types resolve exactly as they do for the package), compiled with
     `pnpm --filter @design-schema/<pkg> exec tsc -p .modules-check/tsconfig.json`

Nothing is checked when no extension declares a module for the platform. The gate reads
generated/components.json (each entry's `extensions[].modules`), so parse must have run.

Usage:  python3 tools/check_modules.py --platform web [--no-typecheck]
Exit 1 on any finding.
"""
from __future__ import annotations

import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "generated"
PACKAGES = ROOT / "packages"
PKG = {"web": "react", "lit": "lit", "rn": "rn"}
CHECK_DIR = ".modules-check"  # inside the package, git-ignored
# What the check program imports so the platform's globals (`__DEV__`) are declared in the program.
PREAMBLE = {"web": [], "lit": [], "rn": ["import 'react-native';"]}


def declared_modules(components: list[dict], platform: str) -> list[dict]:
    """[{component, extension, name, path, signature}] for every module that targets the platform."""
    out = []
    for e in components:
        for ext in e.get("extensions") or []:
            for name, m in (ext.get("modules") or {}).items():
                if m.get("platforms") and platform not in m["platforms"]:
                    continue
                out.append({"component": e["component"]["name"], "extension": ext["name"], "name": name,
                            "path": m["path"], "signature": m["signature"]})
    return out


def exports_name(source: str, name: str) -> bool:
    if re.search(rf"^\s*export\s+(?:async\s+)?(?:function\*?|const|let|var|class)\s+{re.escape(name)}\b", source, re.M):
        return True
    for m in re.finditer(r"^\s*export\s*\{([^}]*)\}", source, re.M):
        names = [part.strip().split(" as ")[-1].strip() for part in m.group(1).split(",")]
        if name in names:
            return True
    return False


def relpath(target: Path, start: Path) -> str:
    """Forward-slash relative path that always starts with ./ or ../ (a bare name would be a package import)."""
    rel = os.path.relpath(target, start).replace("\\", "/")
    return rel if rel.startswith(".") else "./" + rel


def check_program(modules: list[dict], platform: str, check_dir: Path, stubs_dir: Path) -> str:
    """The TypeScript that proves each real export is assignable to its stub."""
    src = check_dir.parent / "src"
    lines = ["// Generated by tools/check_modules.py: assignability of each custom module to its declared stub. Do not edit."]
    lines += PREAMBLE[platform]
    for i, m in enumerate(modules):
        real = relpath((src / m["path"]).with_suffix(""), check_dir)
        stub = relpath((stubs_dir / m["path"]).with_suffix(""), check_dir)
        lines += [f"import * as real{i} from '{real}';",
                  f"import type * as stub{i} from '{stub}';",
                  f"const check{i}: typeof stub{i}.{m['name']} = real{i}.{m['name']};",
                  f"void check{i};"]
    return "\n".join(lines) + "\n"


def tsconfig() -> dict:
    return {"extends": "../tsconfig.json",
            "compilerOptions": {"noEmit": True, "composite": False, "incremental": False},
            "include": ["check.ts"]}


def pnpm() -> str:
    return shutil.which("pnpm") or shutil.which("pnpm.cmd") or "pnpm"


def run(platform: str, typecheck: bool = True, components: list[dict] | None = None,
        packages: Path = PACKAGES, generated: Path = GENERATED) -> list[str]:
    if components is None:
        cj = generated / "components.json"
        if not cj.exists():
            return ["generated/components.json missing — run tools/parse.py"]
        components = json.loads(cj.read_text(encoding="utf-8"))
    modules = declared_modules(components, platform)
    if not modules:
        return []
    findings = []
    pkg_dir = packages / PKG[platform]
    present = []
    for m in modules:
        f = pkg_dir / "src" / m["path"]
        where = f"{m['component']}.{m['extension']}"
        if not f.exists():
            findings.append(f"{where}: module '{m['name']}' expects packages/{PKG[platform]}/src/{m['path']}, which does not exist")
            continue
        if not exports_name(f.read_text(encoding="utf-8"), m["name"]):
            findings.append(f"{where}: packages/{PKG[platform]}/src/{m['path']} does not export '{m['name']}'")
            continue
        present.append(m)
    if findings or not typecheck or not present:
        return findings
    check_dir = pkg_dir / CHECK_DIR
    check_dir.mkdir(parents=True, exist_ok=True)
    (check_dir / "check.ts").write_text(check_program(present, platform, check_dir, generated / "modules" / platform), encoding="utf-8")
    (check_dir / "tsconfig.json").write_text(json.dumps(tsconfig(), indent=2) + "\n", encoding="utf-8")
    p = subprocess.run([pnpm(), "--filter", f"@design-schema/{PKG[platform]}", "exec", "tsc", "-p", f"{CHECK_DIR}/tsconfig.json"],
                       cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if p.returncode != 0:
        out = ((p.stdout or "") + (p.stderr or "")).strip()
        findings.append(f"a custom module does not match its declared signature (packages/{PKG[platform]}/{CHECK_DIR}/check.ts):\n{out[-3000:]}")
    return findings


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--platform", required=True, choices=list(PKG))
    ap.add_argument("--no-typecheck", action="store_true", help="only existence and export checks")
    a = ap.parse_args()
    findings = run(a.platform, typecheck=not a.no_typecheck)
    for f in findings:
        print(f"✖ {f}")
    cj = GENERATED / "components.json"
    n = len(declared_modules(json.loads(cj.read_text(encoding="utf-8")), a.platform)) if cj.exists() else 0
    print(f"{'✖' if findings else '✔'} check_modules ({a.platform}): {n} module(s), {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
