#!/usr/bin/env node
/**
 * Spec sheet: one generated docs page that shows every token value and every component
 * style binding for a theme, resolved in light and dark, with the WCAG contrast of the
 * color pairs that matter.
 *
 * Reads packages/tokens/dist/<theme>/json/tokens.{light,dark}.json (values already
 * resolved, public dotted names) and generated/components.json; writes
 * site/src/content/docs/foundations/spec-sheet.md as plain Markdown + inline-styled HTML
 * that Starlight renders without scripts or extra CSS.
 *
 * Usage: node tools/spec_sheet.ts [--theme calm-precise]
 *
 * Port of tools/spec_sheet.py: same flag, same exit codes, same wording, and the same page
 * bytes (only the "generated by" line names the `.ts` file). Runs under Node's type stripping:
 * annotations only.
 */
import { existsSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expand } from './check_contrast.ts';
import { has, pyFixed, pyGet, pyRstrip, pySorted, pyStr, pyStrip, readText, truthy, writeText } from './lib/py.ts';
import { pyFloatRepr } from './lib/pyyaml.ts';
import { REPO_ROOT } from './lib/root.ts';
import { publicName, shadowCss } from './lib/tokens.ts';
import { contrast } from './oklch.ts';

/** Every path the tool reads or writes. The tests point these at a sandbox. */
export const paths = {
  ROOT: REPO_ROOT,
  DIST: join(REPO_ROOT, 'packages', 'tokens', 'dist'),
  GENERATED: join(REPO_ROOT, 'generated', 'components.json'),
  OUT: join(REPO_ROOT, 'site', 'src', 'content', 'docs', 'foundations', 'spec-sheet.md'),
};

export const DEFAULT_THEME = 'calm-precise';
export const MODES: readonly string[] = ['light', 'dark'];
export const AA_TEXT = 4.5;
export const AA_GRAPHIC = 3.0; // WCAG 1.4.3 normal text / 1.4.11 non-text (icons, borders, focus rings)

const DASH = '—';
const barStyle = (px: number): string => `inline-size: ${px}px; max-inline-size: 100%; block-size: 12px; background: var(--sl-color-accent, #888)`;
const NAME_STYLE = 'display: inline-block; min-inline-size: 13rem; font-family: var(--sl-font-mono, monospace); font-size: 0.85em';
const swatchStyle = (value: string): string =>
  'display: inline-block; inline-size: 1.1em; block-size: 1.1em; vertical-align: -0.2em; ' +
  `border-radius: 3px; border: 1px solid #88888880; background: ${value}`;

export type Tokens = Record<string, unknown>;
export type Modes = Record<string, Tokens>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Dict = Record<string, any>;

export { expand };

// ---------------------------------------------------------------- inputs

/** Theme ids that have a built token dist (a json/tokens.light.json). */
export function distThemes(): string[] {
  if (!existsSync(paths.DIST)) return [];
  return pySorted(readdirSync(paths.DIST).filter((name) => existsSync(join(paths.DIST, name, 'json', 'tokens.light.json'))));
}

export function loadTokens(theme: string, mode: string): Tokens {
  const path = join(paths.DIST, theme, 'json', `tokens.${mode}.json`);
  return existsSync(path) ? (JSON.parse(readText(path)) as Tokens) : {};
}

/** Resolve a public dotted name; `x.default` is the group itself (mirrors tokens.publicName). */
export function lookup(tokens: Tokens, ref: string): unknown {
  return pyGet(tokens, publicName(ref), null);
}

// ---------------------------------------------------------------- formatting

/** `float(s)`: the literals Python accepts, `null` where it raises ValueError. */
function pyFloat(s: string): number | null {
  const t = pyStrip(s).replace(/_/g, '');
  if (!/^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(t) && !/^[+-]?(inf(inity)?|nan)$/i.test(t)) return null;
  return Number(t.replace(/infinity/i, 'Infinity'));
}

/** `round(x)`: half to even, returning an integer. */
function pyRound(x: number): number {
  const floor = Math.floor(x);
  const frac = x - floor;
  if (frac > 0.5) return floor + 1;
  if (frac < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

export function px(value: unknown): number | null {
  if (typeof value === 'string' && value.endsWith('px')) {
    const n = pyFloat(value.slice(0, -2));
    return n === null || !Number.isFinite(n) ? null : pyRound(n);
  }
  return null;
}

export function isColor(value: unknown): boolean {
  return typeof value === 'string' && (value.startsWith('#') || value === 'transparent');
}

function isShadow(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && has(value, 'offsetX');
}

/** A token value as display text; None → em dash. */
export function fmt(value: unknown): string {
  if (value === null || value === undefined) return DASH;
  if (isShadow(value)) return shadowCss(value);
  if (Array.isArray(value)) {
    if (value.length > 0 && value.every((x) => typeof x === 'number')) return `cubic-bezier(${value.map(pyStr).join(', ')})`;
    return value.map(pyStr).join(', ');
  }
  return pyStr(value);
}

/** A fontFamily list as a CSS value usable inside a double-quoted style attribute. */
export function cssFontFamily(value: unknown): string {
  if (Array.isArray(value)) return value.map((f: unknown) => (typeof f === 'string' && f.includes(' ') ? `'${f}'` : pyStr(f))).join(', ');
  return pyStr(value);
}

export function swatch(value: unknown): string {
  return isColor(value) ? `<span style="${swatchStyle(value as string)}"></span>` : '';
}

/** Table cell: swatch + value for colors, plain value otherwise, pipes escaped. */
export function cell(value: unknown): string {
  let text = fmt(value);
  if (isColor(value)) text = `${swatch(value)} \`${text}\``;
  return text.replaceAll('|', '\\|');
}

export function textCell(s: unknown): string {
  return pyStrip(pyStr(truthy(s) ? s : '').replaceAll('\r', '').replaceAll('\n', ' ').replaceAll('|', '\\|'));
}

export function table(headers: string[], rows: string[][]): string[] {
  const out = ['| ' + headers.join(' | ') + ' |', '|' + headers.map(() => ' --- ').join('|') + '|'];
  return out.concat(rows.map((r) => '| ' + r.join(' | ') + ' |'));
}

// ---------------------------------------------------------------- sections

function barRow(name: string, value: unknown): string {
  const n = px(value);
  const bar = n !== null ? `<div style="${barStyle(n)}"></div>` : '';
  return (
    '<div style="display: flex; align-items: center; gap: 0.75rem; margin-block: 0.25rem">' +
    `<span style="${NAME_STYLE}">${name}</span>${bar}<span>${fmt(value)}</span></div>`
  );
}

function bars(tokens: Tokens, names: string[]): string[] {
  // One contiguous HTML block: a blank line would end it and hand the rest to Markdown.
  return names.map((n) => barRow(n, tokens[n])).concat(['']);
}

export function spacingSection(light: Tokens): string[] {
  const keys = Object.keys(light);
  const numbered = keys.filter((k) => /^space\.\d+$/u.test(k));
  numbered.sort((a, b) => Number(a.split('.')[1]) - Number(b.split('.')[1]));
  const aliases = keys.filter((k) => k.startsWith('space.') && !numbered.includes(k));
  const groups: [string, string][] = [
    ['Gaps', 'layout.gap'],
    ['Sections', 'layout.section'],
    ['Insets', 'layout.inset'],
    ['Gutters', 'layout.gutter'],
    ['Max widths', 'layout.maxWidth'],
  ];
  let out = [
    '## Spacing scale',
    '',
    "Bars are drawn at the token's pixel value (wide values clip to the column). " +
      'Components bind to the numbered steps or the `sm`/`md`/`lg` aliases; layout rhythm below is what goes *between* components.',
    '',
  ];
  out = out.concat(['### Steps', ''], bars(light, numbered));
  out = out.concat(['### Aliases', ''], bars(light, aliases));
  out = out.concat(['## Layout rhythm', '']);
  for (const [label, prefix] of groups) {
    const names = keys.filter((k) => k === prefix || k.startsWith(prefix + '.'));
    if (names.length > 0) out = out.concat([`### ${label}`, ''], bars(light, names));
  }
  return out;
}

export function typeSection(light: Tokens): string[] {
  const keys = Object.keys(light);
  const sizes = keys.filter((k) => k.startsWith('font.size.'));
  const lineHeights = keys.filter((k) => k.startsWith('font.lineHeight.'));
  const families = keys.filter((k) => k.startsWith('font.family.'));
  const weights = keys.filter((k) => k.startsWith('font.weight.'));
  const body = cssFontFamily(pyGet(light, 'font.family.body', 'inherit'));
  const normal = pyGet(light, 'font.lineHeight.normal', 1.5);
  const lhText = lineHeights.map((k) => `${k.split('.').at(-1) as string} ${fmt(light[k])}`).join(', ');
  const out = [
    '## Type scale',
    '',
    `Each size is rendered at its own value in \`font.family.body\`, at \`font.lineHeight.normal\` (${fmt(normal)}). ` +
      `Line-height tokens: ${lhText}.`,
    '',
  ];
  for (const k of sizes) {
    const v = light[k];
    out.push(
      '<div style="margin-block: 0.5rem">' +
        `<div style="font-family: ${body}; font-size: ${fmt(v)}; line-height: ${fmt(normal)}">The quick brown fox jumps over the lazy dog</div>` +
        `<div style="font-size: 0.8em; opacity: 0.8"><code>${k}</code> ${fmt(v)} ` +
        `&middot; line height: ${lineHeights.map((lh) => `<code>${lh}</code>`).join(' / ')}</div></div>`,
    );
  }
  out.push('');
  out.push('### Families and weights', '');
  out.push(...table(['Token', 'Value'], [...families, ...weights, ...lineHeights].map((k) => [`\`${k}\``, cell(light[k])])));
  out.push('');
  return out;
}

/** (foreground, background, AA floor) for the pairs that matter, drawn from the tokens present. */
export function contrastPairs(light: Tokens): [string, string, number][] {
  const keys = Object.keys(light);
  const pairs: [string, string, number][] = [];
  const variants = pySorted([...new Set(keys.filter((k) => /^color\.action\.[\p{L}\p{N}_]+\.foreground$/u.test(k)).map((k) => k.split('.')[2] as string))]);
  for (const v of variants) pairs.push([`color.action.${v}.foreground`, `color.action.${v}.background`, AA_TEXT]);
  for (const fg of ['color.foreground', 'color.foreground.muted', 'color.foreground.strong', 'color.foreground.danger', 'color.link']) {
    if (has(light, fg)) pairs.push([fg, 'color.background', AA_TEXT]);
  }
  if (has(light, 'color.border.focus')) pairs.push(['color.border.focus', 'color.background', AA_GRAPHIC]);
  const tones = pySorted([...new Set(keys.filter((k) => /^color\.status\.[\p{L}\p{N}_]+\.background$/u.test(k)).map((k) => k.split('.')[2] as string))]);
  for (const t of tones) {
    for (const [part, need] of [['foreground', AA_TEXT], ['icon', AA_GRAPHIC], ['border', AA_GRAPHIC]] as [string, number][]) {
      if (has(light, `color.status.${t}.${part}`)) pairs.push([`color.status.${t}.${part}`, `color.status.${t}.background`, need]);
    }
  }
  if (has(light, 'color.control.selectedForeground') && has(light, 'color.control.selectedBackground')) {
    pairs.push(['color.control.selectedForeground', 'color.control.selectedBackground', AA_TEXT]);
  }
  if (has(light, 'color.inverse.surface')) {
    for (const k of keys) {
      if (!k.startsWith('color.inverse.') || k === 'color.inverse.surface') continue;
      const graphic = k === 'color.inverse.focus' || k.startsWith('color.inverse.status.');
      pairs.push([k, 'color.inverse.surface', graphic ? AA_GRAPHIC : AA_TEXT]);
    }
  }
  return pairs;
}

export function ratio(tokens: Tokens, fg: string, bg: string): number | null {
  const f = pyGet(tokens, fg, null);
  let b = pyGet(tokens, bg, null);
  if (b === 'transparent') b = pyGet(tokens, 'color.background', null); // ghost etc. — check against the page background, as check_contrast.ts does
  if (!(isColor(f) && isColor(b)) || f === 'transparent' || b === null) return null;
  try {
    return contrast((f as string).slice(0, 7), (b as string).slice(0, 7)); // alpha channel, if any, is ignored
  } catch {
    return null;
  }
}

export function contrastText(modes: Modes, fg: string, bg: string, need: number): string {
  const parts: string[] = [];
  for (const [mode, tokens] of Object.entries(modes)) {
    const r = ratio(tokens, fg, bg);
    if (r === null) parts.push(`${mode} ${DASH}`);
    else parts.push(`${mode} ${pyFixed(r, 2)}:1 ${r >= need ? 'AA pass' : 'AA fail'}`);
  }
  return `on \`${bg}\` (needs ${pyFloatRepr(need)}): ` + parts.join('; ');
}

export function colorSection(modes: Modes): string[] {
  const light = modes.light as Tokens;
  const names = Object.keys(light).filter((k) => k.startsWith('color.') && !k.startsWith('color.palette.'));
  const byFg = new Map<string, string[]>();
  for (const [fg, bg, need] of contrastPairs(light)) {
    if (!byFg.has(fg)) byFg.set(fg, []);
    (byFg.get(fg) as string[]).push(contrastText(modes, fg, bg, need));
  }
  const rows = names.map((k) => [
    `\`${k}\``,
    cell(pyGet(light, k, null)),
    cell(pyGet(modes.dark as Tokens, k, null)),
    (byFg.get(k) ?? [DASH]).join('<br>'),
  ]);
  const out = [
    '## Color roles',
    '',
    'Semantic colors only (the `color.palette.*` ramps are raw material components never reference). ' +
      `The contrast column checks text pairs against WCAG AA ${pyFloatRepr(AA_TEXT)}:1 and icon/border/focus pairs against ${pyFloatRepr(AA_GRAPHIC)}:1; ` +
      'a `transparent` background is checked against `color.background`.',
    '',
  ];
  return out.concat(table(['Token', 'Light', 'Dark', 'Contrast'], rows), ['']);
}

export function styleRows(comp: Dict, modes: Modes): string[][] {
  const props = truthy(pyGet(comp, 'props', null)) ? (comp.props as Dict) : {};
  const styles = truthy(pyGet(comp, 'styles', null)) ? (comp.styles as Dict) : {};
  const rows: string[][] = [];
  for (const [binding, spec] of Object.entries(styles) as [string, Dict][]) {
    const where = [spec.part !== undefined ? `part \`${pyStr(spec.part)}\`` : '', spec.state !== undefined ? `state \`${pyStr(spec.state)}\`` : ''].filter((s) => s !== '').join(', ');
    const description = textCell(pyGet(spec, 'description', null));
    const described = where === '' ? description : description === '' ? `${where}.` : `${where}: ${description}`;
    const tokenRows = (label: string, token: string): void => {
      let refs: string[];
      try {
        refs = expand(token, props);
      } catch {
        refs = [token]; // slot names no enum prop: show it verbatim, values unresolved
      }
      for (const ref of refs) {
        rows.push([
          label,
          `\`${ref}\``,
          cell(lookup(modes.light as Tokens, ref)),
          cell(lookup(modes.dark as Tokens, ref)),
          truthy(pyGet(spec, 'locked', null)) ? 'yes' : 'no',
          described,
        ]);
      }
    };
    tokenRows(`\`${binding}\``, pyGet(spec, 'token', '') as string);
    // A per-value token gets its own row, after the token that covers every other value.
    for (const [value, token] of Object.entries((spec.values ?? {}) as Dict)) tokenRows(`\`${binding}\` (${pyStr(spec.by)}=${value})`, token as string);
  }
  return rows;
}

export function componentsSection(components: Dict[], modes: Modes): string[] {
  let out = [
    '## Components',
    '',
    'Every style binding per component, in `generated/components.json` order. Bindings with a `{prop}` slot are ' +
      'listed once per enum value. *Locked* bindings cannot be overridden per instance.',
    '',
  ];
  for (const entry of components) {
    const comp = entry.component as Dict;
    const title = (truthy(pyGet(entry, 'title', null)) ? entry.title : comp.name) as string;
    out = out.concat([`## ${title}`, '']);
    if (truthy(pyGet(entry, 'id', null))) out = out.concat([`[Component doc](/components/${entry.id as string}/)`, '']);
    const rows = styleRows(comp, modes);
    if (rows.length > 0) out = out.concat(table(['Binding', 'Token', 'Light', 'Dark', 'Locked', 'Description'], rows));
    else out.push('*No style bindings.*');
    out.push('');
  }
  return out;
}

// ---------------------------------------------------------------- page

export function render(theme: string, allThemes: string[], modes: Modes, components: Dict[]): string {
  const others = allThemes.filter((t) => t !== theme);
  let intro =
    `Generated from the built tokens of the **${theme}** theme and \`generated/components.json\`. ` +
    'Every value is the resolved light and dark value a component receives on every platform.';
  if (others.length > 0) {
    intro +=
      ` Other built themes: ${others.map((t) => `\`${t}\``).join(', ')} — regenerate for one of them with ` +
      '`pnpm spec-sheet --theme <id>`.';
  }
  let lines = [
    '---',
    'title: Spec sheet',
    `description: Every token value and every component style binding for the ${theme} theme, resolved in light and dark, with contrast ratios for the color pairs that matter.`,
    'sidebar:',
    '  order: 9',
    '---',
    '<!-- generated by tools/spec_sheet.ts — do not edit by hand -->',
    '',
    intro,
    '',
  ];
  lines = lines.concat(spacingSection(modes.light as Tokens));
  lines = lines.concat(typeSection(modes.light as Tokens));
  lines = lines.concat(colorSection(modes));
  lines = lines.concat(componentsSection(components, modes));
  return pyRstrip(lines.join('\n')) + '\n';
}

export type Args = { theme: string };

/** `argparse` with `RawDescriptionHelpFormatter`: the module's doc comment between the usage and the options. */
const DESCRIPTION = `
Spec sheet: one generated docs page that shows every token value and every component
style binding for a theme, resolved in light and dark, with the WCAG contrast of the
color pairs that matter.

Reads packages/tokens/dist/<theme>/json/tokens.{light,dark}.json (values already
resolved, public dotted names) and generated/components.json; writes
site/src/content/docs/foundations/spec-sheet.md as plain Markdown + inline-styled HTML
that Starlight renders without scripts or extra CSS.

Usage: node tools/spec_sheet.ts [--theme calm-precise]
`;

/** argparse's `--theme THEME`, including its exit code 2 on a bad flag. */
export function parseArgs(argv: string[], prog: string = 'spec_sheet.ts'): Args {
  const usage = `usage: ${prog} [-h] [--theme THEME]`;
  const help =
    `${usage}\n${DESCRIPTION}\noptions:\n` +
    `  -h, --help     show this help message and exit\n` +
    `  --theme THEME  theme id under packages/tokens/dist/ (default ${DEFAULT_THEME})\n`;
  const die: (message: string) => never = (message) => {
    process.stderr.write(`${usage}\n${prog}: error: ${message}\n`);
    throw Object.assign(new Error(message), { exitCode: 2 });
  };
  const args: Args = { theme: DEFAULT_THEME };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] as string;
    if (arg === '-h' || arg === '--help') {
      process.stdout.write(help);
      throw Object.assign(new Error('help'), { exitCode: 0 });
    } else if (arg === '--theme' || arg.startsWith('--theme=')) {
      const value = arg.startsWith('--theme=') ? arg.slice('--theme='.length) : argv[++i];
      if (value === undefined) die('argument --theme: expected one argument');
      args.theme = value;
    } else {
      die(`unrecognized arguments: ${arg}`);
    }
  }
  return args;
}

export function main(argv: string[] = process.argv.slice(2)): number {
  let args: Args;
  try {
    args = parseArgs(argv);
  } catch (e) {
    return (e as { exitCode?: number }).exitCode ?? 2;
  }

  const available = distThemes();
  if (!available.includes(args.theme)) {
    process.stderr.write(
      `✖ theme '${args.theme}' has no built tokens under ${relative(paths.ROOT, paths.DIST)}/ ` +
        `(available: ${available.join(', ') || 'none'}) — run \`pnpm themes\` first\n`,
    );
    return 1;
  }
  if (!existsSync(paths.GENERATED)) {
    process.stderr.write('✖ generated/components.json missing — run tools/parse.ts first\n');
    return 1;
  }

  const modes: Modes = {};
  for (const m of MODES) modes[m] = loadTokens(args.theme, m);
  const components = JSON.parse(readText(paths.GENERATED)) as Dict[];
  mkdirSync(dirname(paths.OUT), { recursive: true });
  writeText(paths.OUT, render(args.theme, available, modes, components));
  const out = relative(paths.ROOT, paths.OUT).replaceAll(sep, '/');
  process.stdout.write(`✔ spec sheet: ${Object.keys(modes.light as Tokens).length} tokens, ${components.length} components → ${out}\n`);
  return 0;
}

const invokedDirectly = process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) process.exitCode = main();
