"""
Pure-Python DTCG token resolver (theme × mode).

Style Dictionary (tokens/build.mjs) is the canonical multi-platform build.
This module exists for the Python side of the house — the parser, the
contrast checker, and (later) the FastMCP server — so they can read the
same source files without a Node toolchain. It also writes a fallback
tokens.css so the docs site works before `pnpm tokens` has ever run.

Usage:
    python3 tools/tokens.py            # resolve + write dist/json + dist/css fallback
    from tokens import load_theme      # load_theme(theme_id, mode) → {dotted.path: {$value,$type}}
"""
from __future__ import annotations

import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES_DIR = ROOT / "tokens" / "themes"
DIST = ROOT / "packages" / "tokens" / "dist"
MODES = ["light", "dark"]
REF = re.compile(r"^\{([a-zA-Z0-9.\-]+)\}$")
RESERVED = {"$type", "$description", "$value", "$extensions", "$deprecated"}


def _deep_merge(a: dict, b: dict) -> dict:
    for k, v in b.items():
        if isinstance(v, dict) and isinstance(a.get(k), dict):
            _deep_merge(a[k], v)
        else:
            a[k] = v
    return a


def themes() -> list[str]:
    """Theme ids, generated by tools/theme.py into tokens/themes/<id>/."""
    return sorted(p.name for p in THEMES_DIR.iterdir() if (p / "base.json").exists())


def modes(theme: str) -> list[str]:
    return [m for m in MODES if (THEMES_DIR / theme / f"{m}.json").exists()]


def load_tree(theme: str, mode: str) -> dict:
    tree: dict = {}
    for f in (THEMES_DIR / theme / "base.json", THEMES_DIR / theme / f"{mode}.json"):
        _deep_merge(tree, json.loads(f.read_text()))
    return tree


def flatten(tree: dict) -> dict[str, dict]:
    """{ 'color.foreground.default': {'$value': ..., '$type': ...}, ... } with inherited $type."""
    out: dict[str, dict] = {}

    def walk(node: dict, path: list[str], inherited_type: str | None):
        t = node.get("$type", inherited_type)
        if "$value" in node:
            out[".".join(path)] = {"$value": node["$value"], "$type": t}
            return
        for k, v in node.items():
            if k in RESERVED or not isinstance(v, dict):
                continue
            walk(v, path + [k], t)

    walk(tree, [], None)
    return out


def resolve(flat: dict[str, dict]) -> dict[str, dict]:
    def get(path: str, seen: tuple[str, ...] = ()) -> object:
        if path in seen:
            raise ValueError(f"Circular token reference: {' -> '.join(seen + (path,))}")
        if path not in flat:
            raise KeyError(f"Unknown token reference {{{path}}} (referenced from {seen[-1] if seen else '?'})")
        v = flat[path]["$value"]
        m = REF.match(v) if isinstance(v, str) else None
        return get(m.group(1), seen + (path,)) if m else v

    return {p: {"$value": get(p), "$type": t["$type"], "raw": t["$value"]} for p, t in flat.items()}


def load_theme(theme: str, mode: str) -> dict[str, dict]:
    return resolve(flatten(load_tree(theme, mode)))


def public_name(path: str) -> str:
    """color.foreground.default → color.foreground (the name components use)."""
    parts = path.split(".")
    return ".".join(parts[:-1] if parts[-1] == "default" else parts)


def css_name(path: str) -> str:
    kebab = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", public_name(path).replace(".", "-")).lower()
    return f"--{kebab}"


def shadow_css(v: dict) -> str:
    return f"{v['offsetX']} {v['offsetY']} {v['blur']} {v.get('spread', '0px')} {v['color']}"


def shadow_rn(v: dict) -> dict:
    """iOS shadow props + Android elevation from one DTCG shadow. Color carries alpha as #RRGGBBAA."""
    color = v["color"]
    alpha = int(color[7:9], 16) / 255 if len(color) == 9 else 1.0
    px = lambda s: float(s[:-2]) if isinstance(s, str) and s.endswith("px") else s  # noqa: E731
    blur = px(v["blur"])
    return {"shadowColor": color[:7], "shadowOffset": {"width": px(v["offsetX"]), "height": px(v["offsetY"])},
            "shadowRadius": blur / 2, "shadowOpacity": round(alpha, 3), "elevation": max(1, round(blur / 4))}


def css_value(entry: dict) -> str:
    v = entry["$value"]
    if entry["$type"] == "shadow":
        return shadow_css(v)
    if entry["$type"] == "cubicBezier":
        return f"cubic-bezier({', '.join(str(x) for x in v)})"
    if isinstance(v, list):  # fontFamily
        return ", ".join(f'"{f}"' if " " in f else f for f in v)
    return str(v)


def camel_name(path: str) -> str:
    parts = public_name(path).replace("-", ".").split(".")
    return parts[0] + "".join(s[:1].upper() + s[1:] for s in parts[1:])


RN_FONT_ALIASES = {"system-ui": "System", "ui-monospace": "monospace"}


def js_value(entry: dict, rn: bool) -> object:
    v = entry["$value"]
    if entry["$type"] == "shadow":
        return shadow_rn(v) if rn else shadow_css(v)
    if entry["$type"] == "cubicBezier":
        return v if rn else f"cubic-bezier({', '.join(str(x) for x in v)})"
    if isinstance(v, list):  # fontFamily
        if rn:
            return RN_FONT_ALIASES.get(v[0], v[0])
        return ", ".join(f'"{f}"' if " " in f else f for f in v)
    if rn and entry["$type"] == "dimension" and isinstance(v, str) and v.endswith("px"):
        return float(v[:-2]) if "." in v[:-2] else int(v[:-2])
    if rn and entry["$type"] == "duration" and isinstance(v, str) and v.endswith("ms"):
        return int(v[:-2])
    return v


def write_js(tokens: dict, path: Path, rn: bool) -> None:
    lines = [f"export const {camel_name(p)} = {json.dumps(js_value(e, rn))};" for p, e in tokens.items()]
    path.write_text("// Generated by tools/tokens.py (fallback); `pnpm tokens` regenerates via Style Dictionary.\n" + "\n".join(lines) + "\n")
    def ts_type(val: object) -> str:
        if isinstance(val, dict):
            return "{ shadowColor: string; shadowOffset: { width: number; height: number }; shadowRadius: number; shadowOpacity: number; elevation: number }"
        return "number" if isinstance(val, (int, float)) else "number[]" if isinstance(val, list) else "string"

    decls = [f"export declare const {camel_name(p)}: {ts_type(js_value(e, rn))};" for p, e in tokens.items()]
    path.with_suffix(".d.ts").write_text("\n".join(decls) + "\n")


def write_dist() -> None:
    for theme in themes():
        for sub in ("json", "css", "js", "rn"):
            (DIST / theme / sub).mkdir(parents=True, exist_ok=True)
        css_parts = []
        for mode in modes(theme):
            tokens = load_theme(theme, mode)
            (DIST / theme / "json" / f"tokens.{mode}.json").write_text(
                json.dumps({public_name(p): e["$value"] for p, e in tokens.items()}, indent=2) + "\n"
            )
            write_js(tokens, DIST / theme / "js" / f"tokens.{mode}.js", rn=False)
            write_js(tokens, DIST / theme / "rn" / f"tokens.{mode}.js", rn=True)
            # Light is the :root default so a page with no attributes still works; dark is opt-in.
            selector = ':root, [data-mode="light"]' if mode == "light" else '[data-mode="dark"]'
            lines = [f"  {css_name(p)}: {css_value(e)};" for p, e in tokens.items()]
            css_parts.append(f"{selector} {{\n" + "\n".join(lines) + "\n}\n")
        # Token-name contract shared by every platform: the dotted public names as a string-literal union, plus
        # helpers to turn a ref into the CSS hook value or the camelCase RN key. Theme- and mode-independent.
        names = [public_name(p) for p in tokens]
        (DIST / "names.d.ts").write_text(
            "// Generated by tools/tokens.py — the dotted token names every theme provides.\n"
            "export type TokenRef =\n  | " + "\n  | ".join(json.dumps(n) for n in names) + ";\n"
            "export declare const TOKEN_NAMES: readonly TokenRef[];\n"
            "/** 'space.lg' → 'var(--space-lg)' */\nexport declare function cssVar(ref: TokenRef): string;\n"
            "/** 'space.lg' → 'spaceLg' (the key in the JS/RN token objects) */\nexport declare function tokenKey(ref: TokenRef): string;\n"
            "/** Resolve a ref against a loaded token object: resolveToken(tokens, 'space.lg') */\n"
            "export declare function resolveToken<T extends Record<string, unknown>>(tokens: T, ref: TokenRef): T[keyof T];\n"
        )
        (DIST / "names.js").write_text(
            "// Generated by tools/tokens.py\n"
            "export const TOKEN_NAMES = " + json.dumps(names) + ";\n"
            "const kebab = (ref) => ref.replace(/\\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();\n"
            "export const cssVar = (ref) => `var(--${kebab(ref)})`;\n"
            "export const tokenKey = (ref) => ref.split('.').map((s, i) => (i === 0 ? s : s[0].toUpperCase() + s.slice(1))).join('');\n"
            "export const resolveToken = (tokens, ref) => tokens[tokenKey(ref)];\n"
        )
        (DIST / theme / "css" / "tokens.css").write_text(
            f"/* Theme: {theme}. Generated by tools/tokens.py (fallback); `pnpm tokens` regenerates via Style Dictionary. */\n"
            + "\n".join(css_parts)
        )
        print(f"✔ {theme}: {len(tokens)} tokens × {len(modes(theme))} modes → {(DIST / theme).relative_to(ROOT)}/")


if __name__ == "__main__":
    try:
        write_dist()
    except (KeyError, ValueError) as e:
        print(f"✖ {e}", file=sys.stderr)
        sys.exit(1)
