"""
Pure-Python DTCG token resolver (theme × mode).

Style Dictionary (tokens/build.mjs) is the only token build: it writes every file under
packages/tokens/dist, including the names.{js,d.ts} contract. The Python fallback that used to
write those files is gone — `pnpm themes` is `node tools/theme.ts && node tokens/build.mjs`.

What is left is the reader, and it is left only for mcp/server.py, the last Python module that
needs one; step 6 of process/typescript-and-currency.md deletes this file with it. Every
TypeScript tool reads tokens through tools/lib/tokens.ts, the port of what is below.

Usage:
    from tokens import load_theme      # load_theme(theme_id, mode) → {dotted.path: {$value,$type}}
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES_DIR = ROOT / "tokens" / "themes"
MODES = ["light", "dark"]
REF = re.compile(r"^\{([a-zA-Z0-9.\-]+)\}$")
RESERVED = {"$type", "$description", "$value", "$extensions", "$deprecated"}


def _deep_merge(a: dict, b: dict) -> dict:
    for k, v in b.items():
        if isinstance(v, dict) and isinstance(a.get(k), dict):
            _deep_merge(a[k], v)
        else:
            a[k] = v
    return a


def themes() -> list[str]:
    """Theme ids, generated by tools/theme.ts into tokens/themes/<id>/."""
    return sorted(p.name for p in THEMES_DIR.iterdir() if (p / "base.json").exists())


def modes(theme: str) -> list[str]:
    return [m for m in MODES if (THEMES_DIR / theme / f"{m}.json").exists()]


def load_tree(theme: str, mode: str) -> dict:
    tree: dict = {}
    for f in (THEMES_DIR / theme / "base.json", THEMES_DIR / theme / f"{mode}.json"):
        _deep_merge(tree, json.loads(f.read_text()))
    return tree


def flatten(tree: dict) -> dict[str, dict]:
    """{ 'color.foreground.default': {'$value': ..., '$type': ...}, ... } with inherited $type."""
    out: dict[str, dict] = {}

    def walk(node: dict, path: list[str], inherited_type: str | None):
        t = node.get("$type", inherited_type)
        if "$value" in node:
            out[".".join(path)] = {"$value": node["$value"], "$type": t}
            return
        for k, v in node.items():
            if k in RESERVED or not isinstance(v, dict):
                continue
            walk(v, path + [k], t)

    walk(tree, [], None)
    return out


def resolve(flat: dict[str, dict]) -> dict[str, dict]:
    def get(path: str, seen: tuple[str, ...] = ()) -> object:
        if path in seen:
            raise ValueError(f"Circular token reference: {' -> '.join(seen + (path,))}")
        if path not in flat:
            raise KeyError(f"Unknown token reference {{{path}}} (referenced from {seen[-1] if seen else '?'})")
        v = flat[path]["$value"]
        m = REF.match(v) if isinstance(v, str) else None
        return get(m.group(1), seen + (path,)) if m else v

    return {p: {"$value": get(p), "$type": t["$type"], "raw": t["$value"]} for p, t in flat.items()}


def load_theme(theme: str, mode: str) -> dict[str, dict]:
    return resolve(flatten(load_tree(theme, mode)))


def public_name(path: str) -> str:
    """color.foreground.default → color.foreground (the name components use)."""
    parts = path.split(".")
    return ".".join(parts[:-1] if parts[-1] == "default" else parts)


def css_name(path: str) -> str:
    kebab = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", public_name(path).replace(".", "-")).lower()
    return f"--{kebab}"


def camel_name(path: str) -> str:
    parts = public_name(path).replace("-", ".").split(".")
    return parts[0] + "".join(s[:1].upper() + s[1:] for s in parts[1:])
